### PR TITLE
Gamepad

### PR DESCRIPTION
**Pull request by cra0zy**
Things I did:
<ul>
<li>Allowed Mac and Linux to use GamePad</li>
<li>Added Name param to GamePad</li>
<li>Added Xbox 360 Wireless Joystick linux config to GamePadCongifurationDatabase</li>
</ul>

### CODE REVIEW

**Comment by Frassle** [comment]
lgtm
New 360 config matches one found in the SDL2 database.
GetName forwards to already implemented methods.
MappedGamePadDriver should function on MacOS and Linux as it uses the platform Joystick interface.

**Comment by Frassle** [comment]
Can someone confirm this change is ok (tested) for OSX and Linux, I don't have access to either at the moment.

**Comment by cra0zy** [comment]
This is taking a while.... :(

**Comment by cra0zy** [comment]
yay merged :dancer:

**Pull request merged**
