### PR TITLE
Text.Json OpenTk.Mathematics support. [WIP] 🚧

### PR DESCRIPTION
**Pull request by Rainboi64**
### Adding support for System.Text.Json to Opentk.Mathematics [WIP] 🚧

* Adds necessary attributes for properly serializing members of Opentk.Mathematics using the System.Text.Json tools.
* Focuses primarily on the OpenTk.Mathematics namespace.
* Solves recursive loops originated by properties, and includes fields for serialization.

### Testing status

* Serialization and deserialization for randomly generated data, across a big sample rate
* Manual testing, using personal work in progress projects
* Serialization and deserialization results compared to other third party tools, and libraries

### Comments

* currently since opentk is still running in dotnetcoreapp3.1/dotnetstandard2.1, doing this will require a custom converter class for every item for serialization, and that's because the `[JsonInclude]` attribute is not supported in the current version.

### CODE REVIEW

**Comment by Rainboi64** [comment]
Due to current limitations of the API, closing until opentk is updated to net5.

**Comment by NogginBops** [comment]
You can retarget PR this to the opentk 5.0 branch if you want. Otk 5 targets .net 5 so the api should be there.

**Comment by Rainboi64** [comment]
that's what I'll be doing!
Sorry for all the fuss, this is my first PR ;P

**Comment by NogginBops** [comment]
No problems, contributions are always welcome. And you can't get it first the right time (especially when it comes to git).

**Pull request closed without merging**
