### PR TITLE
Start of bug fix for window state

### PR DESCRIPTION
**Pull request by KinsonDigital**
## **Description of bug fix:**
Fixes a bug where after setting the **WindowState** to **WindowState.Fullscreen**, setting the **WindowState** to anything other setting has no effect.  The window will remain in full screen mode.

## **Which part of OpenTK does this affect:**
Native Window/GLFW.  Specifically in the **OpenTK.Windowing.Desktop** namepsace in the **NativeWindow** class.

### Testing:

* Testing is done manually.  This involves setting the border to the state **WindowState.Fullscreen** then back to any other state in the **WindowState** enumeration.  The window should change from fullscreen to all other window state types.

Use the test matrix below for testing the different window state scenarios.   The **From State** column is the window state that the window is in **before** going to the desired state.  The **Going To State** is of course the state that the window is going to be in once the window is put into that state with both the mouse interaction as well as programmatically.

|From State 	|Going To State     |Works On Win   |Works On Linux |
|----------------|-------------------|------------------|------------------|
|Minimized     |Normal        	    |Y   	                |                          |
|Minimized     |Maximized           |Y   	                |   	                   |
|Minimized     |Fullscreen            |Y   	                |   	                   |
|Normal          |Minimized           |Y   	                |   	                   |
|Normal          |Maximized           |Y                         |   	                   |
|Normal          |Fullscreen            |Y                         |   	                   |
|Maximized     |Minimized           |Y   	                |   	                   |
|Maximized     |Normal                |Y   	                |   	                   |
|Maximized     |Fullscreen            |Y   	                |   	                   |
|Fullscreen       |Normal                |Y   	                |   	                   |
|Fullscreen       |Minimized           |Y   	                |   	                   |
|Fullscreen       |Maximized           |Y   	                |   	                   |
### Comments

Plan on collaborating with Offenbash with this for linux testing.

### CODE REVIEW

**Comment by KinsonDigital** [comment]
## Scenarios to think about:

1. If the window border was set to fixed to prevent users from maximizing the window, should the window actually be maximized when setting the `WindowState` to `Maximized` when the state is coming **FROM** `Fullscreen`?
2. If the window is in `Fullscreen` mode, and the `WindowState` is being set to `Minimized`, should the window go back to `Fullscreen` when the user clicks the status bar icon to "restore" the window?
    * When conversating with **Noggin_bops**, it was mentioned that other operating systems might not have the same behavior for this scenario.  This will have to be researched to see if **linux** and **windows** "restore from minimized" behavior are the same.

**Comment by KinsonDigital** [comment]
For commit [6101a85](https://github.com/opentk/opentk/pull/1183/commits/6101a8508f4ba7ca971c609e05448c26a0e1f3fd), added a `Dispose(true)` call inside of the `NativeWindow.Close()` method.  

If the user is not using the `using` pattern, then resources would not be called correctly when closing the window programmatically.

**Comment by KinsonDigital** [comment]
For commit [5bedaa9](https://github.com/opentk/opentk/pull/1183/commits/5bedaa9569eb95f4d9c0c1974ed858878fc95843), added `Dispose(true)` in the `NativeWindow.OnCloseCallback(Window* window)` call.  This is to ensure that resources are being disposed properly when closing the window via the mouse button as well as using Alt+F4 on windows.

**Review by varon — COMMENTED** [review]
Had a great discussion on Discord about this. It seems like we missed some window event hooks that we can use instead of polling. Will try to change to those.

**Pull request merged**
