### PR TITLE
Stop taking X locks on display when attempting MakeCurrent() calls.

### PR DESCRIPTION
**Pull request by SparkusK**
### Purpose of this PR

* Remove ```using (new XLock(display)) { <stuff...> }``` wrappers from ```Glx.MakeCurrent()``` calls.
* Affects OpenTK/Platform/X11/X11GLContext.cs

### Testing status

* Automated tests still work
* Simple application that renders a color-gradient triangle still works, too.

### Comments

* Attempting to take the X lock on the display will prevent glXMakeCurrent in the driver to take the internal lock that it needs, which leads to deadlocks. Since there's no apparent valid reason for this, it should be removed.

### CODE REVIEW

**Comment by varon** [comment]
Thanks for the PR! Always nice to see new contributions!

There might be one lock you missed: 
https://github.com/SparkusK/opentk/blob/0c1082892da6781bdbc0b9fcf44cf7713cd2f5cc/src/OpenTK/Platform/X11/X11GLContext.cs#L370

I think we can probably drop this lock, because we're not going to lock if we make the context current later on anyway.

**Comment by varon** [comment]
@Nihlus @Frassle - I think this is probably good to merge.

Could either of you run a test against a slightly larger project?

**Comment by Frassle** [comment]
Change seems ok to me. I don't have any projects atm that would test this better than just a simple cube draw.

**Comment by Nihlus** [comment]
Agreed, looks fine. I don't have any complex projects which use the native backend either (save for one, but that shouldn't be affected by this PR). @peppy Perhaps osu! is a good test candidate?

**Comment by leezer3** [comment]
openBVE appears to work just fine with these patches applied, and that's a very complex openGL 1.1 app.

**Comment by varon** [comment]
Thanks, @SparkusK!

Really excellent contribution!

**Pull request merged**
