### PR TITLE
Sdl2 fixes

### PR DESCRIPTION
**Pull request by mrhelmut**
This PR pushes a couple fixes that have been applied to MonoGame:
- MonoGame/opentk#5
- MonoGame/opentk#4
- MonoGame/opentk#2 (duplicate already merged of #335)
- MonoGame/opentk#1 (duplicate of #334)

It pushed a couple of already merged commits and a pending one. Let me know if you wish that I try to separate everything.

### CODE REVIEW

**Comment by cra0zy** [comment]
> Let me know if you wish that I try to separate everything.

Please do, and thank you for doing this.

**Comment by mrhelmut** [comment]
Sorry, I'm not sure to know how to extract these commits from this branch. :/ I've been overconfident. ^^'

**Comment by cra0zy** [comment]
> Sorry, I'm not sure to know how to extract these commits from this branch. :/ I've been overconfident. ^^'

The command is: `git cherry-pick <commit>`.

For example you want to merge https://github.com/mrhelmut/opentk/commit/898e4ca11f992da3d9765dfe5ec3dcb4d2de0031 to the newest branch. You would do:
```
git checkout develop
git branch deas
git checkout deas
git cherry-pick 898e4ca11f992da3d9765dfe5ec3dcb4d2de0031
git push -u origin deas
```

In case commit is from other repo all you have to do is:
```
git remote add otherrepo https://github.com/otherrepo.git
git fetch otherrepo
```
before running the commands so that git can find the commit.

Want to try it out or should I do it?

**Comment by mrhelmut** [comment]
Thanks for the doc! I wasn't quite sure about the cherry picking process.

Let me know if these are correct:
#350 #351 #352 

(closing this one)

**Pull request closed without merging**
