### PR TITLE
Change to .NET 4.5

### PR DESCRIPTION
**Pull request by xanather**
Change to using .NET 4.5.

Most of the changes were done automatically through visual studio the .NET target version conversion.
The prefer 32-bit XML in some of the project files is normal (it is equivilent to .NET 2.0 functionality).

Also included changes here https://github.com/opentk/opentk/pull/215 .

All projects compile successfully.

### CODE REVIEW

**Comment by xanather** [comment]
Hmm not sure why the build bot is failing

**Comment by Frassle** [comment]
I think @LaylConway hit some issues with it as well.

**Comment by xanather** [comment]
I'm not sure if I'm reading it right, but its the Mono 2.0 compilation that is failing which is expect isn't it?

**Comment by xanather** [comment]
Is there anything wrong with this PR? Is it preferable to have a separate branch instead? (can do that too). I just thought that since https://github.com/opentk/opentk/issues/206 is fixed in this then it should be OK to push to the main branch.

The bot is failing for Mono 2.0 testing which should be expected, the other Mono 3.x version is successful.

Whoever manages the bot may need to drop the Mono 2.0 testing. If we're dropping .NET 2.0 support.

**Comment by Frassle** [comment]
> Is there anything wrong with this PR? 

Code changes look ok. The Travis failure is concerning but I need to look into that, might just be the 2.0 build.

> Is it preferable to have a separate branch instead? (can do that too).

Yes! For sure! I'm well aware of the impending death of .NET 2.0 but we can't just drop support for it.

> Whoever manages the bot may need to drop the Mono 2.0 testing. If we're dropping .NET 2.0 support.

I'll see if I can get it to drop the 2.0 build if targeting the new branch. Don't worry about it for now.

**Comment by xanather** [comment]
I am still slightly new to git/github. I'm trying to submit a PR to a new branch but it will only let me choose existing ones. Maybe a new branch needs to created on the main repo first before I can submit a PR to it?

**Comment by Frassle** [comment]
net45 branch created!

**Comment by xanather** [comment]
Creating another PR...

**Pull request closed without merging**
