### PR TITLE
[5.0] OpenTK.Compute changes 

### PR DESCRIPTION
**Pull request by NepNet**
### Purpose of this PR

* Upgraded project to .NET5 and C# 9
* Replaced all function UIntPtr type with nuint (introduced in C# 9)
* OpenTK.Compute is affected

### Testing status

Works as before but no need to cast to UIntPtr for size or offset type argument

### Comments

* Removed the tests for OpenCL from the solution

### CODE REVIEW

**Comment by NogginBops** [comment]
It looks like this PR has some merge conflicts.
Other than that this PR looks good.

**Comment by NepNet** [comment]
The conflicts seem to be caused by the fact I removed the CLTests project from the solution

**Comment by frederikja163** [comment]
@NogginBops Does this still look good? I havent really been using opentk.compute at any point in time, so having your eyes on this again would be appreciated.

**Comment by NogginBops** [comment]
I think this is looking good. It will probably lead to some pain when trying to merge the current master into opentk 5.0.
But if this version glxcl interop is "complete" then we can just discard the opentk 4 version when we get to the merge.
Would need @NepNet s confirmation that this is a "complete" version of the GLxCL interop before that, but if that is the case then I think we can merge this.

**Comment by NepNet** [comment]
It should be complete

**Comment by NogginBops** [comment]
Ok, then this is good. Great PR!
Merging.

**Pull request merged**
