### PR TITLE
Remove bindings from Git

### PR DESCRIPTION
**Pull request by Nihlus**
This PR removes the binding files (GL.cs, GLEnums.cs, etc) from Git, and adds their generation as a one-time build step. Furthermore, the readme has been updated with instructions to run `build.sh` at least once.

### CODE REVIEW

**Comment by VPeruS** [comment]
How much is it cost to generate this files?

**Comment by Nihlus** [comment]
@VPeruS A couple of minutes, and it's a one-time cost.

**Comment by Frassle** [comment]
Looks ok to me. Can probably do some more cleverness about rebuilds and rerunning the binding but that can come (much) later.

**Comment by Nihlus** [comment]
Alright, let's get her merged.

**Pull request merged**
