### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by HughPH**
Changed wording around availability of OpenTK, to clarify that Android & iOS support is limited.

### CODE REVIEW

**Comment by NogginBops** [comment]
This wording might lead people to think that the current versions of OpenTK actually run on android and iOS which they don't (thanks Xamarin).

**Comment by HughPH** [comment]
> This wording might lead people to think that the current versions of OpenTK actually run on android and iOS which they don't (thanks Xamarin).

That's the point of the edit: the original text just says it works on Android, my revised text adds that it's limited. We could simply remove Android and iOS altogether.

**Comment by NogginBops** [comment]
I think that the readme can mention Xamarin incompatibility and link to somewhere where you can get more information. Because technically you can get opentk running on android and iOS, it's just that it's limited to opentk 1.0

**Comment by varon** [comment]
This is a good change in principle, but I would avoid 'advertising' the fork, because at the end of the day we really don't want to be using it.

Try something like:

>An old, unsupported version of OpenTK 1.0 may be included in the [Xamarin](https://docs.microsoft.com/en-us/xamarin/graphics-games/game-development/) Android and iOS distribution. This is not endorsed, supported or maintained by this project.
>
>Adding support for mobile again is planned in the future, but is somewhat complicated by Apple's deprecation of OpenGL. We welcome contributions to re-add support for these platforms.

**Review by varon — APPROVED** [review]

**Comment by varon** [comment]
Thanks, super simple and great!

**Pull request merged**
