### PR TITLE
Add a DegToRad and a RadToDeg constant for easier conversion between radians and degrees.

### PR DESCRIPTION
**Pull request by DamienIsPoggers**
### Purpose of this PR

The purpose of this PR is to bring a quality of life function to quaternions. Quaternions, when converted to euler angles, are always in radians, and while having the conversion to euler angles alone is very helpful, it's not easy working in radians when you need to look at the angles directly.

By adding the conversion into the class itself, it allows easy use of getting and editing angles in a more understandable format without having to manually convert the vector back and forth.

### Testing status

Did testing by editing rotations of multiple objects over time, one object in radians, one in degrees and got identical quaternions every frame.

### CODE REVIEW

**Comment by NogginBops** [comment]
Thanks for making this PR!
Unfortunately I think we'd rather like to make the conversion between radians and degrees more convenient in general, rather than adding additional overloads to math functions. Creating overloads for degrees sets the precedent that every function that takes a radians should have a degrees overload. Which isn't really ideal.

Instead I'd like to see facilities for easier and more convenient radians to degrees conversions. For example making `MathHelper.RadiansToDegrees()` into just a `MathHelper.R2D` constant. And potentially adding something like `Vector3.R2D` (though it's unnecessary with `MathHelper.R2D` as we could do `vec * MathHelper.R2D`).

If you are willing to pivot this PR (or make a new PR) into this more general direction I would be happy to merge it! 🙂

**Comment by DamienIsPoggers** [comment]
Honestly, yeah that probably would be easier to do than to add a lot of overloads. I'll just add them as constant and revert the quaternion changes.

**Comment by DamienIsPoggers** [comment]
Made the changes and did a small conversion test to check that passed but didn't test anything big.

**Comment by NogginBops** [comment]
Good stuff, though I think the standard `MathHelper.Rad2Deg` should be `float` as that is what people are mostly going to be using and always casting to float is a pain. 
We can add a separate `MathHelper.Rad2Degd` for `double`.

**Comment by NogginBops** [comment]
Perfect! CI passes, merging. Ping me on discord if you want a contributor tag.

**Pull request merged**
