### PR TITLE
[Win] GDI handle leak

### PR DESCRIPTION
**Pull request by alonevampire**
Fixed Cursor related GDI handle leak

### CODE REVIEW

**Comment by alonevampire** [comment]
The Cursor property for WinGLNative leaks GDI handles.

It uses the function GetIconInfo (https://msdn.microsoft.com/en-us/library/windows/desktop/ms648070(v=vs.85).aspx) to which creates bitmaps that are not properly deleted after the call to CreateIconIndirect, which copies the bitmaps to the icon it creates. The change I made was to call DeleteObject on the bitmaps after CreateIconIndirect, as they were no longer needed.

**Comment by Frassle** [comment]
Can you fix the commit history so this is just pulling in your commits?

**Comment by alonevampire** [comment]
I'd love to, but I'm new to git. Can you give me an idea of how to do what you're asking?

**Comment by Frassle** [comment]
Well you can either do an interactive rebase (git rebase -i --onto origin/master) and then just select your commits from that.

Or and probably easier, make a new blank branch based on the latest OpenTK master (git checkout -b new_branch origin/master) and cherry-pick your commits onto it (git cherry-pick dfa2c37a2f60458741fab83e426443cb8f7b5e07; git cherry-pick 4958996f124bfbf6fd3c442299878341e1b0a13d) then push that new branch to this pull request
 (git push origin new_branch:refs/heads/master).

**Pull request closed without merging**
