### PR TITLE
New build system

### PR DESCRIPTION
**Pull request by varon**
This follows on from #413 and #417.

This adds FAKE as a build system, allowing a one-step build for all NuGet packages.

Unit tests will be re-added to the build in a subsequent PR.

### CODE REVIEW

**Comment by varon** [comment]
This will need some more work with the specific quirks of the CI system. I'll continue tomorrow.

**Comment by varon** [comment]
CI is now correctly building OpenTK and OpenTK.GLControl.

We'll need to resolve the OpenTK.GLWidget building, as this has some difficulty with the GTK# dependencies, which I believe it currently assumes to be installed on the system. Further testing will be needed, but can be done in a subsequent PR.

The unit tests will be re-added in a subsequent PR once this is merged.

**Comment by forki** [comment]
I'm currently investigating https://github.com/fsprojects/Paket/issues/1818 and saw you still have a packages.config in tests/OpenTK.Tests

**Comment by varon** [comment]
Thanks for the spot, @forki. 

At the moment, this PR isn't building the tests at all. We're going to swap them over to xUnit/FsCheck anyway, so they're still sort of in limbo here - I'll get rid of that dangling file as part of those changes in a follow-up PR which restores the testing.

It also shouldn't be affecting the current build at all, as we're selecting the projects from the 'src' directory only.

**Comment by forki** [comment]
Yeah it was only affecting VS.

**Comment by cra0zy** [comment]
@varon rebase the PR to develop so I can see the changes properly.

**Comment by varon** [comment]
@cra0zy  Done.

**Comment by cra0zy** [comment]
You didn't give build.sh executable permissions. Other than that I don't see anything else sticking out, tho I don't know much about FAKE.

**Comment by varon** [comment]
Great! I'll fix that.

**Comment by cra0zy** [comment]
Merging!!! Don't forget about https://github.com/opentk/opentk/pull/417#issuecomment-237535615

**Pull request merged**
