### PR TITLE
[4.0] Add StructLayout to Color4

### PR DESCRIPTION
**Pull request by devvoid**
Add StructLayout to Color4, as mentioned in #833. This should make the class safe to pass to native functions.

### CODE REVIEW

**Comment by devvoid** [comment]
That second commit wasn't meant to go to this branch, I'll see if I can remove that.

**Comment by DylanFPS** [comment]
Thanks so much for your contribution! We have decided that we are going to refrain from merging this as `struct`s implicity have the attribute you are adding in this PR, sorry. We hope to see more from you and your eager eye in the future though :)

**Comment by jvbsl** [comment]
But there is no default Layout? Without the attribute the CLR is free to rearrange the fields as it sees fit(e.g. optimization purposes - which they try to do a lot more with .Net Core btw...) Or do Alignment stuff.
So I think it would be much better to specify the Layout, to be sure that it will work in the future as well.

**Comment by jvbsl** [comment]
Alright thanks. I think my googling skills are rusty, how on earth could I not find that^^

Nevertheless I think it is stupid to apply it by default, because of possible lose of performance optimizations, but nvm.

In my opinion I like to apply the layout still, because it makes everything clear. Like with "private" before a field which is not really necessary, because it gets applied automatically as well...

**Comment by varon** [comment]
I'd agree with I'm in favour of applying this. It makes it more clear and discoverable to the user - a little like using explicit `private` modifiers or avoiding short ifs.

We also currently define it on the Vector classes; which this should be consistent with.

**Pull request closed without merging**
