### PR TITLE
Use MSBuild on modern Mono platforms

### PR DESCRIPTION
**Pull request by Nihlus**
MSBuild replaced xbuild as the primary build tool on modern Mono platforms (>= Mono 5.0). FAKE does not yet detect this itself, however, and uses xbuild by default.

This PR adds a workaround in the build script that checks the installed version of Mono and whether or not msbuild is present, and sets an environment variable which FAKE recognizes. In the case that the Mono installation is >= 5.0 but msbuild is not present, xbuild is used instead.

The issue has been reported to FAKE ([#1570](https://github.com/fsharp/FAKE/issues/1570)), and the workaround can be removed once FAKE has corrected this.

### CODE REVIEW

**Comment by varon** [comment]
This unfortunately now causes the build script to fail to execute now if mono is not installed, which is entirely possible on windows, or in the future, on platforms running dotnet instead of mono.

`./build.sh: line 35: mono: command not found`

Can we address that?

**Comment by Nihlus** [comment]
Yes, that's fairly trivial to solve. I'll add a fix.

**Comment by Nihlus** [comment]
I added two additional checks - one for the presence of Mono, and if that succeeds, one for awk which is used to extract the Mono version. That should cover our bases in terms of dotnet and bash users on Windows. For the latter, I also changed from "which" to "command -v" which is a builtin bash command instead of which, which is an external tool.

**Comment by varon** [comment]
Still receiving an error, not sure the 'or' fallthrough works as expected here on Line 41.

```
./build.sh: line 41: mono: command not found
```

Based on what was said at https://github.com/fsharp/FAKE/issues/1570 - We should try just updating FAKE to the latest version to see if it solves the issue.

**Comment by Nihlus** [comment]
FAKE has been updated to its most recent verson in #529 with no change, unfortunately. There appears to be a bug somewhere in the chain. I see the problem, though, I missed inverting the check for Mono - it enters the block if Mono is _not_ present, not the other way around. Oops!

**Comment by Nihlus** [comment]
Ah, my bad. FAKE updated without me noticing, and it is now detecting msbuild correctly.

**Pull request closed without merging**
