### PR TITLE
Invert Y axis on all GamePad

### PR DESCRIPTION
**Pull request by mrhelmut**
Re-submission of #334

@cra0zy

### CODE REVIEW

**Comment by cra0zy** [comment]
@amulware I am ok with us inverting Y axis to match XNA axes direction, are you ok with it?

**Comment by amulware** [comment]
Just to be clear, this is a breaking change for all code that uses gamepads then, right?

Is there some sort of standard or reasoning for which way the axis are supposed to be going?
Or is the argument only the one in #334, about XNA and XInput being different?

**Comment by mrhelmut** [comment]
The OpenTK documentation states that ```GamePad``` was intended to be modeled after XNA (http://www.opentk.com/doc/input/gamepad). This is why I submitted this PR in the first place.

**Comment by amulware** [comment]
Very well then. I was hoping there was some some... "important" reason. But I'm fine with this.

**Comment by wcdeich4** [comment]
Just a suggestion - there could be a settings variable to switch back & forth which way the Y-Axis is measured & the default could be how it works in XNA

**Comment by cra0zy** [comment]
> Just a suggestion - there could be a settings variable to switch back & forth which way the Y-Axis is measured & the default could be how it works in XNA

No.

**Pull request merged**
