### PR TITLE
IFormattable implementations for vectors

### LINKED ISSUE #1481: Formatting in interpolated string of Vectors
### Description

It'd be nice to be able to forward format strings specified in interpolated strings to each individual component. A common usecase may be to display each component with, let's say, two digits. Right now, one has to manually call `$"{Vec.X:0.00}, {Vec.Y:0.00}, {Vec.Z:0.00}"`. It would be better to be able to do `$"{Vec:0.00}"`.

### Repro steps

Define some kind of vector and make an interpolated string with a format string like this `$"{Vec:0.00}"`.

### Expected behavior

The formatting is applied to each component.

### Actual behavior

The code compiles, but the formatting string is ignored.

### Related information 

* Wsl2 in Windows11
* Nuget version 4.7.4
* .Net 6.0.302
* Workarounds specified above

### PR DESCRIPTION
**Pull request by g7ChoGXh**
### Purpose of this PR

Fixes #1481.
Implements the changes wanted in #1481 by implementing the IFormattable interface for all vectors. The implementation delegates the actual formatting to the vectors scalar type, passing on the `format` and `formatProvider` parameters.

### Testing status

Manual testing has been done.

### Comments

You can @ me in the Discord server if you have any questions.

### CODE REVIEW

**Comment by NogginBops** [comment]
I think we should also provide a `ToString(string format)` overload similar to what the microsoft docs do
https://learn.microsoft.com/en-us/dotnet/api/system.iformattable?view=net-7.0

**Comment by g7ChoGXh** [comment]
If we provide an overload like `ToString(string format)` we should also provide `ToString(IFormatProvider formatProvider)` as this is what is done with the numeric types in the BCL: https://learn.microsoft.com/en-us/dotnet/api/system.single.tostring?view=net-7.0#system-single-tostring

However, both overloads can also be provided by extension methods on `IFormattable` which can be done easily in user code when the need arises.

**Comment by g7ChoGXh** [comment]
We could also implement `IFormattable` for other types in Mathematics, e.g. the matrices.

Coming back to the code, I think that if there is a good way to get the `ListSeparator` out of the `IFormatProvider` we should do that instead of getting it from the current culture.

**Comment by NogginBops** [comment]
> If we provide an overload like `ToString(string format)` we should also provide `ToString(IFormatProvider formatProvider)` as this is what is done with the numeric types in the BCL: https://learn.microsoft.com/en-us/dotnet/api/system.single.tostring?view=net-7.0#system-single-tostring
> 
> However, both overloads can also be provided by extension methods on `IFormattable` which can be done easily in user code when the need arises.

If this is the standard way to expose this API then I think we too should expose it like that. It's much better for users to not have to write their own extension methods.

**Comment by g7ChoGXh** [comment]
I changed the `ToString`s in Vector2 as an example of what I would change `ToString` the Mathematics types. `GetListSeparator` in `MathHelper` now has a method that attempts to get the `ListSeparator` out of an `IFormatProvider`. I currently see no better way of achieving this than what I have implemented, which will fall back on the current culture if no list separator can be obtained. If you see a better way, please let me know, otherwise I would add this implementation to the other types (vectors, matrices, etc.).

**Comment by NogginBops** [comment]
I've looked a little bit at the `IFormatProvider` issue and I'm not sure if there is a better way, will take an extra look before merging this PR.

As for the overloads in Vector2, they look good.

**Comment by NogginBops** [comment]
Didn't find any better way of getting the list separator. This looks good to me, merging.

**Pull request merged**
