### PR TITLE
Fix windows build script, prevent fatal crash when a joystick with >64 buttons is connected

### PR DESCRIPTION
**Pull request by tyronx**
### Purpose of this PR

As discussed in issue #1020 
It is not the most elegant solution, but since no new major features will be added to OpenTK 3.x and stability is of greater importance, probably still a good idea to merge. 

Also couldn't build with the default FAKE, had to update to a later version. FAKE apparently had a bug where it didn't recognize the path of the newer .net framework versions.

### Testing status

* A build with those fixes included is currently installed at several hundred users through Vintage Story

### CODE REVIEW

**Comment by varon** [comment]
Thanks for the PR @tyronx!

Seems we've got a build failure on CI, possibly due to pathing issues.

Could you try run a local build after running `git clean -fdx` and see what you get?

**Comment by varon** [comment]
@tyronx bump

**Comment by tyronx** [comment]
oh, i guess i also have to push the FAKE 4.6x binaries

**Comment by tyronx** [comment]
The travis ci issue does not look like my fault. Some tool is missing/broken there, by the looks of it

**Comment by varon** [comment]
Thanks. Will do a merge + release of this for you tomorrow!

**Pull request merged**
