### PR TITLE
NUnit Tests from Manuli and Wcdeich4

### PR DESCRIPTION
**Pull request by wcdeich4**
This pull request adds the NUnitTest project with example Vector3 and Matrix4 unit tests written by Wcdeich4 & Manuli respectively.  After this is merged in, the unit testing framework is in place, so each developer can make separate Pull Requests to the main repo in the future.

(I wanted to make a few more Vector3 tests before this Pull Request, but I'm relocating for work, so I may be extremely busy the next few weeks & thought it best to get the unit test framework added now to enable everyone to add unit tests)

### CODE REVIEW

**Comment by amulware** [comment]
There are a bunch of changes to the solution file. I'm not an expert on this, but some of them may not be desirable. Could someone with more experience in this check the file?

**Comment by wcdeich4** [comment]
Basically all that was done was to add NUnit 2.6.4 + NUnitTestAdapter 2.6.4 & the NUnitTests project w/ 2 test classes.  Of course I'll welcome @cra0zy or anyone to double check the Package Manager console installed things properly. 

Now, NUnitTestAdapter is probably what made the most changes b/c it enables Visual Studio & Xamarin to detect NUnit tests & display them in the Test Explorer like they were normal Microsoft Testing Framework unit tests.  One reason I wanted to get this pull request submitted now is b/c after this is done, anyone can add unit tests by just adding another test class to the NUnitTes project.  But we  have to have the framework added for people to do that.

**Comment by cra0zy** [comment]
The solution file is alright, Visual Studio just likes to update it(and reorganize it while it's at it).

@wcdeich4 Can you please name the tests project "OpenTK.Tests"?

**Comment by wcdeich4** [comment]
@cra0zy Ok. Might be few couple days,  like I mentioned, I'm in the middle of moving from one city to another right now.

**Comment by wcdeich4** [comment]
OK, I think I've got the name changed correctly. Sorry to take so long. Flying from Gainesville FL to Seattle WA was quick, but it took 2 weeks to get internet in my net apartment + another week of being so busy @ work I barely  had time to eat, breathe & sleep...

**Comment by cra0zy** [comment]
Merging, thanks @wcdeich4 !!!

**Comment by wcdeich4** [comment]
I was looking at the source online & noticed the NUnitTests folder still exists (https://github.com/opentk/opentk/tree/develop/Source/NUnitTests) along side the OpenTK.Tests folder.  I think there may have been a minor GIT error pushing from the local copy on my hard drive to my github repo before merging.  Anyhow, we can just delete the NUnitTests folder (and of course make sure the .sln knows it's gone)

**Comment by wcdeich4** [comment]
I figured it out - the NUnitTests project was completely removed inside Visual Studio, but the files were left just sitting there in GIT, so here is a new PR to fix it.  [](https://github.com/wcdeich4/opentk/pull/1)

**Comment by cra0zy** [comment]
I fixed it directly in the repo, don't worry.

**Comment by wcdeich4** [comment]
Good

**Pull request merged**
