### PR TITLE
Simplify Transpose() method.

### PR DESCRIPTION
**Pull request by mtosoftware**
Instead of accessing row variables directly I felt it would be much easier to just use the column properties. The Column0 and Column1 properties have been created, might as well use them.

I know that I'm supposed to use the template but this is such a quick fix.

### CODE REVIEW

**Comment by varon** [comment]
Thanks for the PR, @mtosoftware ! No problem on using the template or not. Your judgement call was right here.

You're also right that this looks cleaner, but using those properties actually slows things down that part of code a whole lot! With the changes you've made, we'd now be making an extra 2 method calls per transpose call, and we're also passing around way more data (due to the use of completed structs instead of updating in-place).

We always try to prioritize speed above prettiness, especially on the implementation details of library-level math functions. Please don't be discouraged though. It's nice work, just not 100% aligned with our general direction on the design.

If you can give us some benchmarks that show it's the same speed or faster than the current version, we'd be happy to merge it.

**Comment by mtosoftware** [comment]
@varon Thanks for such a quick reply. I wasn't aware that it would really be affecting the speed so much.

If speed is a concern, wouldn't you rather remove the column properties all together?

**Comment by jvbsl** [comment]
Well if people want to use them they still can. And sometimes people really need Vectors exactly that way. But internally functions should be as Performant as possible.

@varon I did a quick test and the old code is nearly 3 times faster(ofc both codes don't really take that long). But I want to use that situation to indicate that the current Implementation often uses functions with ref/out variables as the most basic Implementation. Which prevents inlining and costs us a lot of performance we could possibly gain by implementing the basic implementations with return values(on stack) and copying input parameters(on stack). Because the copy operation on stack can often be removed by inlining...

**Comment by varon** [comment]
@mtosoftware 
We're fine providing more convenient but slower APIs, but the fastest one we offer should be as fast as possible. For example, we provide operators for vector maths, even though these are significantly slower than using `ref` methods. (at least in theory).

@jvbsl 
We always absolutely love performance related improvements, so if you've got some ideas, we'd love to see them implemented.

**Pull request closed without merging**
