### PR TITLE
Bring forward 3.x binding generators to 4.0

### PR DESCRIPTION
**Pull request by glopesdev**
### Purpose of this PR

* Bring back the 3.x binding generators to allow for intermediate release of OpenTK 4.0 with new windowing + netcore support.

### Testing status

* This PR will bring back the old code verbatim, so there is no intention to write tests at the moment beyond the existing integration tests.

### Comments

* The point of this PR is to have working GL bindings for the new OpenTK 4.0 release.
* First step is to update and build 3.x generator projects.
* Second step will be to weave the 3.x generator output into the current project structure (including namespace changes, etc).

---
This change is [Reviewable](https://reviewable.io/reviews/opentk/opentk/1004)

### CODE REVIEW

**Comment by varon** [comment]
Reviewing this now

**Comment by varon** [comment]
It works! Amazing stuff @glopesdev.

Issues:
1) Running builds isn't quite reproducible. Had to do a `git reset HEAD --hard` to not encounter compile errors between builds.
2) Context creation is straightforward, but we might want to try and improve the API a bit.

Can we include something like this class in the graphics library project?

```cs
public sealed class GlfwBindingsContext: IBindingsContext
    {
        [DllImport("glfw3.dll")]
        private unsafe static extern IntPtr glfwGetProcAddress(byte* procame);

        public unsafe IntPtr GetAddress(IntPtr funcname)
        {
            return glfwGetProcAddress((byte*)funcname);
        }
    }
```

Finally doing something like `new GL().LoadBindings(new GlfwBindingsContext());` is a little wierd to initialize a static class.

I know we don't have static interfaces, but perhaps we can provide a static convenience method that does this instead?

3) DLL had to be renamed and added manually to the output directory, but might be solved by or relate to this: #1000 .

Otherwise, top notch work. This is super clean and works great! Can't wait to merge.

**Comment by glopesdev** [comment]
I agree with all these points. The API for creating context and binding them to the GL entry points could definitely use some cleanup, I only left it as-is to minimize changes in the code (this was how things were done in 3.x).

In fact, I've been looking more closely at the 3.x codebase and the management and creation of graphics context was probably the biggest architectural bottleneck of the entire API. Solving it correctly will allow for a clean separation of concerns between bindings and windowing, which was simply not possible in 3.x.

I'm currently completing this exercise and will have more to say about this soon which can most likely weave into this PR and beyond.

**Comment by varon** [comment]
Excellent. Thanks a ton as always @glopesdev . Looking forward to getting this in!

**Comment by glopesdev** [comment]
@varon I've started cleaning up and refactoring the PR, almost there. I have two remaining questions/observations:

1. I noticed the rename of the bindings project to `OpenToolkit.OpenGL`. I completely agree this project was overdue for a rename, but may I suggest we rename it to `OpenToolkit.Graphics` instead? The reason is that this is actually the root namespace of that project. We need it to be `OpenToolkit.Graphics` because inside that namespace we have `OpenToolkit.Graphics.OpenGL`, `OpenToolkit.Graphics.OpenGL4`, `OpenToolkit.Graphics.ES20`, etc. The root namespace is `OpenToolkit.Graphics` because inside that we assemble all classes and interfaces that are common across specific bindings. This also stays closer to the original OpenTK naming conventions.

Assuming this makes sense, I would rename it in the next few commits and make sure all project references are correct, etc.

2. I agree there should be a convenience implementation of `IBindingsContext` in the GLFW project. To avoid taking on a dependency of the OpenGL bindings project, I am considering moving the very small and generic `IBindingsContext` interface to the `OpenToolkit.Core` project. Any objections?

**Comment by glopesdev** [comment]
It seems like the CI tests failed, but due to a completely unrelated error of approximating Box2 multiplication epsilons. Nothing to do with the current changes, but might be worth double-checking these tests in the context of the math APIs. On my machine the same test runs fine, so I wonder if this could be Travis trying out the build in different hardware?

**Comment by frederikja163** [comment]
I have begun converting some of my projects over to the output of this PR, its working great so far, however GL.ShaderInfoLog seems to throw a CLR error every time i call it, i have tried from pretty much empty projects aswell to ensure that it isnt my code. I have no clue myself what could be causing this.

**Comment by glopesdev** [comment]
@frederikja163 you are correct, I was also able to reproduce it over here. It's strange, this binding was working fine in 3.x (i just checked) and modifications were minimal. I'll have a look and post here what i find, hopefully with a fix.

**Comment by glopesdev** [comment]
Ok, just a quick heads-up: this is affecting all `GL` bindings which return a `string` argument, it must be something with Rewrite, but will have to dig deeper.

**Comment by glopesdev** [comment]
@frederikja163 as a reference, the following code returns a valid error on my environment:

```c#
int status;
var v = GL.CreateShader(ShaderType.VertexShader);
GL.ShaderSource(v, "hello shaders");
GL.CompileShader(v);

GL.GetShader(v, ShaderParameter.CompileStatus, out status);
if (status == 0)
{
    var error = GL.GetShaderInfoLog(v);
    Console.WriteLine(error);
}
```

Let me know if you get it to work.

**Comment by frederikja163** [comment]
I still havent been able to make this PR work whenever a string is returned after the newest commit
Not sure wether or not this is just due to my project not referencing the right DLLs or something tho. Otherwise this PR is really strong and i approve of the bindings it generates.

**Comment by glopesdev** [comment]
@frederikja163 did you try cloning the repo from scratch to a new environment? If this doesn't work, can you share details of your compiler tools? VS version, etc? Did you try running the example code I posted? It might be that there is some edge case that I couldn't figure out, so I would love to fix it or understand it if possible.

**Comment by frederikja163** [comment]
Good news, it works! Im happy to merge if this is not WIP anymore

**Comment by glopesdev** [comment]
@frederikja163 I'm happy for this to be merged. There seems to be a conflict with the OpenTK.sln file. Should I rebase first or can you guys figure out the merge?

**Comment by frederikja163** [comment]
Im not sure how to solve these merge conflics, so if you want to fix it from your side, for sure go ahead with it!

**Comment by varon** [comment]
This passes tests from both @frederikja163 and @deccer .

Thanks so much @glopesdev for all of the outstanding work and incredibly useful PR.

We hope to see many more in the future!

**Pull request merged**
