### PR TITLE
Support OpenTK on Tizen platform

### PR DESCRIPTION
**Pull request by an87li**
1. Add new project files for Tizen
2. Add condition compilation TIZEN in AL/ES11/ES20/EGL/SDL2 for finding right library name on Tizen
3. Add condition compilation TIZEN for Sdl2 and Sdl2NativeWindow initialize on Tizen

### Purpose of this PR

* Description of feature/change.
Porting OpenTK to [Tizen platform](https://en.wikipedia.org/wiki/Tizen), make OpenTK could work on Tizen platfrom. 
The native library names of Tizen are different with the exsiting code, do some changes for that:
Firstly, Add a new project, it define constant 'TIZEN' and build opentk.dll for Tizen for Tizen.
Secondly, Add condicional compilation in souce code, if define 'TIZEN' then using the tizen library name to compile opentk.dll.
* Which part of OpenTK does this affect (Math, OpenGL, Platform, Input, etc).
This change affact OpenAL, ES11, ES20, SDL2, EGL
* Links to screenshots, design docs, user docs, etc.
Using SDL2 as the window and input platform backend of OpenTK on Tizen platform.
The usage of opentk is same as before.

### Testing status

* Explanation of what’s tested, how tested and existing or new automation tests.
ES20 and OpenAL had been tested on Tizen, I made a rotated globe sample with ES20 and made a music player sample with OpenAL, they are both running well on Tizen.
The test project of opentk build failed (run ./build.sh ), so I can't do automation test.

### Comments

* Any other comments to help understand the change.
This change will not affect other platform, just generate a new opentk library that can be run on tizen.

### CODE REVIEW

**Comment by Nihlus** [comment]
Hey there!

Thank you for your work - however, if you're using Mono, these changes are redundant since Mono uses Dll remapping for these library names, and will discover the correct one at runtime as specified in the OpenTK.dll.config file. If you are having issues running OpenTK without these changes, try editing that file first.

On top of that, we're going to move to targeting .NET Standard 2.0 fairly soon, which would render these changes obsolete. We're trying to move away from multiple projects and conditional compilation as much as possible.

**Comment by an87li** [comment]
Hi, thank you for you reply.
Now Tizen is using  .net core, you may know that .net core don't support DllMap [#930](https://github.com/dotnet/coreclr/issues/930) So I can't find the right library via DllMap.

If don't use conditional compilation, how to find the right library? 
please talk more kindly~

**Comment by Nihlus** [comment]
We're working on a solution that can resolve the library name at runtime based on the operating system and load the correct functions - it's being tested in a separate branch. 

Adding more conditional compilation will, unfortunately, just complicate things further when we do port the entire library.

**Comment by an87li** [comment]
Oh, Great!
It will be better, Which branch is it, Can I check out to that branch now?

**Comment by Nihlus** [comment]
Sure thing - it's over here: https://github.com/Nihlus/opentk/tree/netstandard-dynamic-loading
Unfortunately, it's fallen behind somewhat due to the lack of manpower. It'll be revived in the future when we have time.

**Comment by an87li** [comment]
I found a work around for loading correct library while running the program  on netstandard. [AssemblyLoadContext.LoadUnmanagedDllFromPath ](https://github.com/dotnet/corefx/issues/3054)
It can load library, if function return handle it means the correct library is found,

I holp this will help you

**Comment by varon** [comment]
@an87li  - Thanks so much for the PR and work. We'd definitely merge if it wasn't for the netcore stuff incoming soon.

@Nihlus @Frassle  - Should we close this in light of the .net core changes incoming?

**Comment by Nihlus** [comment]
@varon Yes, although it'd be nice to keep around as a reference if we do want to look at Tizen support again.

**Comment by varon** [comment]
@Nihlus  - it's still going to be on the PR history anyway.

@an87li Thanks again, we hope we can deliver the .Net core for you soon! If you'd like to help out in other areas, that's definitely the one that would benefit you the most!

**Comment by qmfrederik** [comment]
FYI - A new API, `NativeLibrary`, is planned for .NET Core which should make loading native (unmanaged) libraries much easier. See dotnet/corefx#17135 for more details.

If you think this would be relevant/useful to you, would you mind upvoting the issue in the corefx repo? Thanks!

**Comment by Nihlus** [comment]
@qmfrederik While useful, and a promising development, it's not a part of .NET Standard, which OpenTK will be targeting. We're currently looking into using an already-developed solution.

**Pull request closed without merging**
