### PR TITLE
Use Windows Virtual Keys instead of Scancodes

### LINKED ISSUE #579: Input Bug: Wrong keydown events when fn + function keys (or special keys) are pressed on laptops
### Description

Wrong keydown events when fn+keys (or special keys like volume control) are pressed on laptops.
For example:
   On Alienware M17 notebook:
      -Fn+F4 (Increase Screen Brightness) gets keydown event for Key.Number5
      -Button for decrease volume (not a fn combination), gets Key.Quote
      -Button for increase volume (not a fn combination), gets Key.X
     -Fn + F9  gets Key.BackSlash
     -Fn + F12 gets Key.Escape
     -Etc (every fn + function key (or notebook special key) gives a wronk keydown event.)

Note: This is not a new issue, this happens on old versions too, and it happens on every laptop that I've tested in (3 in total).

### Related information 

* Operating system: Windows 7 (Home premium & Professional)
* SDL or Native backend: Native (?)
* What version of OpenTK (Installer, NuGet, Source Code): Last from source code (and previous ones)
* What runtime (.NET Framework, CoreCLR, Mono): .NET Framework

### PR DESCRIPTION
**Pull request by tyronx**
### Purpose of this PR

* Fixes #579 on Windows but comes with the drawback that OpenTK no longer maps keys to their physical location on the keyboard, that dilemma was discussed in PR #269. I guess ideally the dev should be able to choose whether he wants to use scancodes or virtual keys, maybe through a boolean flag. This PR could be a basis for that.

### Testing status

* I dare say the changes are well tested as these changes are in use in my game for over a year already.

### Comments

* As mentioned, not entirely sure if this PR should be merged as-is or if the new behavior should be made configurable

### CODE REVIEW

**Comment by leezer3** [comment]
Question please:
How exactly does this handle keyboard layouts which contain keys which aren't QWERTY?

(e.g. Cyrillic or Japanese)

Am I correct in thinking that these are mapped to the nearest positional QWERTY key, as opposed to returning the 'pictorial' (wrong word, can't think of a better one....) character on the key?


Before merging, this would also want to be checked, and changed to be consistant on all other platform backends/
IIRC X11 has a similar issue, but I'd have to check that.

**Comment by tyronx** [comment]
No, this does return the 'pictorial' character on the key, depending on your current keyboard layout of your OS, of course.

**Comment by varon** [comment]
Thanks for the PR, @tyronx. It's really great to see contributions like this.


I think having this functionality available would be highly advantageous and very useful, but we want to be careful about how we go about exposing it. Swapping indiscriminately to virtual keys would presumably break a lot of behaviour that depends upon the physical location of keys, such as 'WASD' being used for FPS-style movement.

I would suggest that we expose this as follows:
```csharp
var keyState = Keyboard.GetState();
// current
keyState.IsKeyDown(Key.A);
// virtual
keyState.isVKeyDown('a');
```

We want to work out the exact details, but taking a `char` instead of a `Key` seems to make more sense here.

We would also need to implement the other platforms before we can merge this.

@Frassle might have some good suggestions here.

**Comment by Frassle** [comment]
I'd definitely be hesitant changing the current behaviour in such a big way. IsVKeyDown sounds reasonable, although it could still take a Key enum rather than a char. Taking a char just begs the question of is 'a' the same as 'A'?

IsKeyDown should probably be warned against, VKeys are nearly always better. Maybe we even deprecate IsKeyDown and remove it after some time?

Also yes other platforms ought to be implemented as well but I'd actually be ok with us exposing this as "Experimental windows only" thing for now. Just leave the IsVKey methods for other platforms as "raise NotYetImplemented". If the framework is in place on master and people are using it on windows might be more likely to get some help doing the other platforms.

**Comment by leezer3** [comment]
Can't we expose this through the configuration namespace?

This lets us keep all existing function calls identical.
Just set to the old method as default, and either document as a Windows only thing, or raise an exception as suggested above (I don't like the exception idea at all....)

IMHO adding a new method group is going to be nothing but confusing and an unnecessary API change to boot.

**Comment by Frassle** [comment]
@leezer3 good idea. Add it to ToolkitOptions.
```
        /// <summary>
        /// Set if Input.Key refers to virtual keys, or us-en scan codes (legacy and default behaviour).
        /// </summary>
        public bool UseVirtualKeys { get; set; }
```

Sound ok? Then we can fail at Init if that's set to true for any unsupported platform (for now, eventually we should support them all with virtual keys)

**Comment by Nihlus** [comment]
Minor nitpick, but if we do implement a new method set, I would argue that we should not needlessly abbreviate things. `IsVirtualKeyDown` is preferable to `IsVKeyDown`.

**Comment by varon** [comment]
The problem with the configuration approach is that we lose the ability to use both at the same time, which the alternative method would offer instead.

Consider the case where we wanted 'wasd' movement, but typing for chat.

@Nihlus Sure, but can we think of any more terse name for that? It's typically something called an awful lot.

**Comment by leezer3** [comment]
@varon
Using both at the same time is IMHO a recipie for massive trouble.
All it takes is one misplaced call to the alternate method and you have a stupidly hard to find bug.....

**Comment by Frassle** [comment]
> Consider the case where we wanted 'wasd' movement, but typing for chat.

If you want wasd movement "properly" you should be asking the user to key bind by virtual key. Chat should never by done by KeyDown checks, you should be listening to char events, that's the only way to ensure you get correct treatments of shifts and combining characters (not sure we give a good hook into this, but we shouldn't encourage using KeyDown checks).

So not sold on that, like @leezer3 says supporting both at once sounds like a recipe for screwing up.

**Comment by Nihlus** [comment]
I'd prefer the ability to choose between the two systems, but it should be made abundantly clear which one you're using. Having different method names with different calling conventions seems generally sufficient, and it is at the end of it the responsibility of the programmer to understand the tools they're using.

**Comment by leezer3** [comment]
r.e. WASD + chat
To me at least different keys doing different things depending on the application context is absolutely mad.

I think the configuration option provides sufficient clarity as to which is in use.
@nihilus I think you'ee forgetting that plenty of apps/ games have multiple coders involved. (And in my case masses of unintelligible junk left behind by a predecessor ;p ) 
All it takes is a mistake or two different approaches,  and I think doing it the method way will only lead to increased support requwsts.

**Comment by Nihlus** [comment]
Thank you for you contribution! Currently, the `develop` branch is frozen while we work on the 4.0 release, and we are not accepting pull requests to it. All current pull requests should be based on that branch, or should be updated to be based on it.

In order to avoid clutter in our pull requests, we're going to be closing any pull request that isn't targeting 4.0 on the 31st of July, 2018. Please rebase your pull request before then.

**Pull request closed without merging**
