### PR TITLE
Fix parameter order inside Transform(Matrix3, Vector3)

### PR DESCRIPTION
**Pull request by cryovat**
### Purpose of this PR

* Description of feature/change.

I noticed after copying the code from `Vector3` to `Vector2` while preparing #1011 that the parameter order inside `Transform(Matrix3, Vector3)` was reversed, such that it called `Transform(ref Vector3, ref Matrix3)` instead of the correct method. 

This resulted in a left handed multiplication instead of the expected right handed one.

* Which part of OpenTK does this affect (Math, OpenGL, Platform, Input, etc).

Math

* Links to screenshots, design docs, user docs, etc.

Current state on Master:
image

### Testing status

The code compiles, and Go To Reference leads to the correct method.

### Comments

* Any other comments to help understand the change.

I hope this doesn't cause lots of hair pulling for people with existing code relying on this :/

### CODE REVIEW

**Comment by frederikja163** [comment]
just like for #1011 we probably want tests for this one aswell

**Comment by cryovat** [comment]
When run against c9cad3a83aa2ecd19d68bc099f8ae4bb5da46c65 on **master**:
```
[xUnit.net 00:00:02.01]     OpenToolkit.Tests.Vector3+Multiplication.Vector3-Matrix3 multiplication using left-handed notation is consistent across overloads [FAIL]
[xUnit.net 00:00:02.03]     OpenToolkit.Tests.Vector3+Multiplication.Vector3-Matrix3 multiplication using right-handed notation is consistent across overloads [FAIL]
  X OpenToolkit.Tests.Vector3+Multiplication.Vector3-Matrix3 multiplication using left-handed notation is consistent across overloads [39ms]
  Error Message:
   FsCheck.Xunit.PropertyFailedException :
Falsifiable, after 1 test (0 shrinks) (StdGen (1120357875,296708054)):
Original:
((-0,023116456; 0,38902462; -0,19325593)
(0,9078741; 1E-45; -0,51007164)
(-0,7172171; 0,97220016; 0,18451881),
 (-0,26614758; 0,67984873; 0,64664733))

---- Assert.Equal() Failure
Expected: (0,14566183; -0,57146496; 0,97115326)
Actual:   (0,15958294; 0,52513266; -0,17601836)
  Stack Trace:
```

Test passes with the change in 9175d72. I added a test for the right handed matrix multiplication as well for consistency.

**Comment by frederikja163** [comment]
So the tests are currently passing or no?

**Comment by cryovat** [comment]
The test does not pass on the current code in master.

The test passes after the change in the pull request.

**Comment by varon** [comment]
Does this result in compile errors for people using the old API, or just different behavior?

**Comment by varon** [comment]
CI is passing on Appveyor, so I'm okay to merge if we can answer.

**Comment by leezer3** [comment]
It'd be different behaviour- Both methods are defined, and perform either left or right-handed multiplication.

Correcting is the best solution, but I'd suspect this has probably crept into a heck of a lot of openGL tutorials, which will likely give a nasty workload.

Old code calls this method:
https://github.com/opentk/opentk/blob/9149fe5728ed2e59897411e5a7280a66434aa531/src/OpenToolkit.Mathematics/Vector/Vector3.cs#L958

Revised code calls this:
https://github.com/opentk/opentk/blob/9149fe5728ed2e59897411e5a7280a66434aa531/src/OpenToolkit.Mathematics/Vector/Vector3.cs#L1016

**Comment by cryovat** [comment]
I'm not sure what to think in this case; if it was a widespread problem, it would surely have been noticed and reported before now.

Most likely people have either been using the overload taking arguments by reference, or the multiplication operator (which calls the former internally). It feels like tutorials would naturally gravitate towards mathematical syntax. For instance: https://opentk.net/learn/chapter1/6-transformations.html#matrix-vector-multiplication

Renaming them to `TransformLeft` and `TransformRight` was suggested on Discord. Another option could potentially be to mark it for a few releases with something like:

```csharp
[Obsolete("Previous versions of OpenTK multiplied the parameters in reversed order, " +
          "please check its usage.", false)]
```

**Comment by leezer3** [comment]
I'd agree with the rename.

4.0 is major breaking anyways- Completely remove the old methods, and there will be a specific compiler error, not a hard to find bug.
The suggested naming is far clearer too.

**Comment by deccer** [comment]
No other math library is using `TransformLeft` or `TransformRight`, makes no sense imho.

What about using operator overloading to implement both ways of operations?

**Comment by cryovat** [comment]
As with ca7b1bb in #1011, I had the parameter order in the left handed unit test wrong. I think this came down to making a mess of things when trying to untangle my code into two separate pull requests, and going back and forth in this feature branch to check the behavior.

I'm not sure what happened though, as the unit test failure above shows that the unit test had the correct parameter order prior to making the pull request. :/

Lessons learned: write tests first next time, and parameter order is hard! Sorry for the inconvenience.

Note that the original bug still remains valid.

**Comment by ThomasD13** [comment]
I agree with leezer3. Rather rename it (which is okay with 4.0) to give developers a chance to pickup and apply the bugfix properly, instead of letting them search the cause for "weird" acting graphical objects/ "bugs".

**Comment by varon** [comment]
Resolved by #1092

**Pull request closed without merging**
