### PR TITLE
Restructure OpenTK repository

### PR DESCRIPTION
**Pull request by varon**
This is a follow on from #413. See also #360 for more information.

This re-works the layout of the repository to match that used by the build script.

If review of this is desired, I'd suggest going through each commit in turn. They've been kept as small as possible to minimize the per-commit changes, and should adequately summarize what was done.

There are two points of interest in these changes:

First, the removal of the 'optional dependencies' folder. As we're focusing on distributing a NuGet package, rather than having people build this from source, these can easily be relocated onto the website or linked to in the README.  Ultimately, I would like to see optional 'OpenTK.Opt.*" packages, using the [NuGet native system ](https://docs.nuget.org/consume/support-for-native-projects) with each of the binaries presented in a cross-platform way, making for easy addition into any project.

Second is the removal of the separate OpenTK.Android and OpenTK.iOS _solutions_. This was done to avoid maintaining duplicate code, and the corresponding _projects_ have been added to the main solution.

On my PC, both Release and Debug builds are compiling with all tests passing with these changes.

### CODE REVIEW

**Comment by varon** [comment]
Note that the CI build will fail at present, as it attempts to compile the Android and iOS projects as part of the main solution.

This should be fixed when we introduce the new build system in the next PR.

**Comment by varon** [comment]
@cra0zy - Still waiting for a merge on this and #418.

**Comment by cra0zy** [comment]
3 things:
 - "tests" solution folder should be "Tests", everything else is capitalized
 - Rename "OpenTK" project to "OpenTK.Desktop", create a new shared project named "OpenTK", and move the classes Android, iOS and Desktop projects have in common to it
 - About the "GLControl" and "GLWidget" projects, do we need to have "OpenTK." in front of them? Also how about creating a solution folder for them?

**Comment by varon** [comment]
Thanks, @cra0zy.

For the tests folder and shared projects, I'm happy to change it, but can we do that after #418, as that depends upon this PR.

For GLControl and GLWidget, I've kept the OpenTK. in front of them as:
 - this matches the root namespaces for the projects
 - this matches the NuGet package Ids.

**Comment by varon** [comment]
@cra0zy I've double checked the naming. It seems all of the root folders are lower case, while all project folders are cased to match the project names and NuGet packages.

**Comment by cra0zy** [comment]
I am not talking about the folder, but the solution folder, ie: https://github.com/opentk/opentk/blob/develop/OpenTK.sln#L22 first "tests" should be "Tests", the second one should remain "tests".

**Comment by cra0zy** [comment]
@varon So.... want me to do the changes? You seem quite slow...

**Comment by varon** [comment]
@cra0zy That would be super helpful if you can. Things are incredibly busy at the moment.

**Pull request merged**
