### PR TITLE
[3.x] Allow use of Virtual Keys on Windows

### PR DESCRIPTION
**Pull request by tyronx**
### Purpose of this PR

This PR adds a backwards compatible mechanic to allow a game window to use windows virtual keys instead of physical keys, as the latter causes issues on some laptops with extended keyboards. We've had cases where the volume control would trigger the 'B' key and the likes. This PR fixes this when constructing the game window with the flag GameWindowFlags.UseVirtualKeys.

* Which part of OpenTK does this affect: Input

### Testing status

* Code itself is tested, the cherry picked merge not well yet. Will be shipping this with Vintage Story 1.16, in about 2-3 weeks it should be well tested.

### CODE REVIEW

**Comment by tyronx** [comment]
1.16 is now shipped, works flawlessly so far, so removing draft status

**Comment by NogginBops** [comment]
I'm guessing this isn't a problem on Linux and Mac?
I'm fine with this only supporting windows but it would be nice to know if this is a problem on other operating systems.

**Comment by tyronx** [comment]
No, this is only a windows issue.

**Comment by NogginBops** [comment]
Thanks a ton for these improvements!
Looked through the code a last time and it looks good to me!
Merging.

**Pull request merged**
