### PR TITLE
Split FsCheck data generators into a helper library

### PR DESCRIPTION
**Pull request by Nihlus**
This PR splits the FsCheck generator and assertion classes out into a helper library that can be used for both F# and C# tests alike. Furthermore, it adds a new test to the Bezier curve tests to demonstrate how the generator would be accessed through C#.

This allows more flexible C# unit tests to be written, while maintaining the versatility of F# for generating test data.

### CODE REVIEW

**Comment by Nihlus** [comment]
Could someone pull this and help me figure out why it isn't building? It's working fine locally.

**Comment by Nihlus** [comment]
Looks like it has to do with how F# treats type overloading when it's not in the same namespace. Will investigate.

**Comment by Frassle** [comment]
Looks ok, is this based on top of the latest paket install run to minimize diffs?

**Comment by Nihlus** [comment]
No - give me a minute and I'll fix it.

**Comment by Nihlus** [comment]
@Frassle Done.

**Comment by Frassle** [comment]
LGTM

**Pull request merged**
