### PR TITLE
Add github issue template

### PR DESCRIPTION
**Pull request by varon**
This should improve the quality of issue reports.

### CODE REVIEW

**Comment by cra0zy** [comment]
Don't ever merge your own stuff... You did some things wrong in the template which I didn't get the chance to tell you about...

**Comment by varon** [comment]
While I generally agree with the idea, I think a bit of flexibility is reasonable. In this case, it's clear that no harm was done by this as no code or project changes were involved. 

This template was taken directly from another repository. Further enhancements and adjustments can easily be added later, as you've done in #421.

**Comment by cra0zy** [comment]
> While I generally agree with the idea, I think a bit of flexibility is reasonable. In this case, it's clear that no harm was done by this as no code or project changes were involved.

You should not merge your own stuff unless it's really important.

> This template was taken directly from another repository. Further enhancements and adjustments can easily be added later, as you've done in #421.

You can say that for everything, but you are in a team now, don't just randomly do stuff on your own.

**Comment by varon** [comment]
Equally so, by that point, you ought to trust your team members with trivial enhancements.

I'm strongly in favour of and a degree of reasonable autonomy by team members. It helps keep things moving.

During the maintainer meeting, we discussed the rules for merging PRs. These are:
>When to merge:
One maintainer for smaller changes/ smaller internal API changes.
Two maintainer for PUBLIC API Changes. 

As I'm a maintainer, we have an approval of one maintainer, so I've merged this in.

**Pull request merged**
