### PR TITLE
Improve Issue Template

### PR DESCRIPTION
**Pull request by cra0zy**

### CODE REVIEW

**Comment by varon** [comment]
Removal of the known workarounds section seems a bit strange. This is generally useful in helping track down what causes the bug. It also allows others who are suffering from the same issue to bypass it while waiting for a release. Relegating this to a minor point decreases the likelihood of people filling it in.

Aside from that, the branch/versioning changes are good.

**Comment by cra0zy** [comment]
> Removal of the known workarounds section seems a bit strange. This is generally useful in helping track down what causes the bug.

It's not removed, it's moved down under related information...

**Comment by varon** [comment]
>removal of the known workarounds **section**. 

Emphasis on **section**. I specifically acknowledged it was moved down in the next sentence.

**Comment by cra0zy** [comment]
> Emphasis on section. I specifically acknowledged it was moved down in the next sentence.

Ups sorry, didn't realize it, anyway workarounds won't always be present, and in most cases aren't present, there is no point of making a section for them when they might not even exist.

> It also allows others who are suffering from the same issue to bypass it while waiting for a release. Relegating this to a minor point decreases the likelihood of people filling it in.

I disagree, all the information in related information are important, and if they manage to skip adding a workaround because they didn't read that part, then they have also skipped adding a bunch of other useful information.

**Pull request merged**
