### PR TITLE
[4.0] Implement 'unmanaged' constraint

### PR DESCRIPTION
**Pull request by FreezyLemon**
### Purpose of this PR

This PR removes the runtime checks (`BlittableValueType<T>.Check` and the like) for types that can be used in interop and replaces them with the new and shiny `unmanaged` constraint for generic types. ([more info](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/generics/constraints-on-type-parameters#unmanaged-constraint))

### Comments

This is blocked until the Mono compiler has support for this language feature (C# language version 7.3).

### CODE REVIEW

**Comment by varon** [comment]
Has mono caught up yet? This would be good to merge.

**Comment by Nihlus** [comment]
Mono's preview branch has - we'll need to adjust Travis to compensate (unless that was covered by another PR, can't recall).

**Comment by varon** [comment]
It's been done and builds on CI. So it's working then. I'm happy to merge as it's for 4.0, so shouldn't break anything anyway.

**Comment by varon** [comment]
In other words, feel free to go ahead and merge @Nihlus , as you've been more in touch with 4.0 than I have.

**Comment by Nihlus** [comment]
Travis needs to have its Mono version set to preview before we can safely merge, looks like it wasn't done in another PR.

**Comment by varon** [comment]
This commit seems to have the change as part of the PR? https://github.com/opentk/opentk/pull/771/commits/bfb4d2551e7bfc7022e6b38b1571720ec22e50be

**Comment by Nihlus** [comment]
Oh, silly me. :man_facepalming: Yeah, all good.

**Pull request merged**
