### PR TITLE
Fix broken Android and iOS builds

### PR DESCRIPTION
**Pull request by akrolsmir**
Seems like Android and iOS builds have been broken on the develop branch for a while.

### CODE REVIEW

**Comment by varon** [comment]
@akrolsmir Awesome to see new contributors!
Did you manage to figure out how to get iOS or Android working?

**Comment by Nihlus** [comment]
Exclusively fixes for removed obsolete code - seems simple enough :D Looks good to me.

**Comment by akrolsmir** [comment]
Thanks! I'm trying to port an existing opentk project onto Android. The demo Android app compiled (and crashes  during runtime, but I think that's unrelated to opentk). Didn't have the Mac server set up for iOS but everything else compiled successfully in think. 

Eventually it'd be nice to have build tests to verify Android/iOS - I saw an issue filed for it somewhere, but I know y'all are already stretched thin.

**Comment by tzachshabtay** [comment]
@akrolsmir just in case you haven't heard of it, Xamarin Live Player (https://www.xamarin.com/live) was released a few months ago, it apparently lets you develop for ios without a mac (you'll still need a mac for deploying though). Haven't tried it myself yet, so not sure how reliable it really is/if it works with OpenTK.

**Pull request merged**
