### PR TITLE
Enforce use of explicit access modifiers

### PR DESCRIPTION
**Pull request by Nihlus**
This PR enforces the use of explicit access modifiers in the codebase. This change is in line with the MSDN C# style guidlines, and generally improves clarity of access.

### CODE REVIEW

**Comment by Frassle** [comment]
> MSDN C# style guidlines

Explicit modifiers is fine be me but I can't find the MSDN style guide your referring to. Might be good to add a point about using explicit modifiers and linking to the style guide your referring to in the contributing wiki page (https://github.com/opentk/opentk/wiki/Contributing)

**Comment by Nihlus** [comment]
@Frassle Ah, right - that particular rule comes from the CoreFX style guide. Varon and I have talked about adopting a more explicit and extensive style guide based on that and MSDN. 

https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/coding-style.md 

I'll see about fixing up the wiki page. 

_Sent from my OnePlus ONEPLUS A3003 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by varon** [comment]
This is a really nice change. Good to see. Explicit modifiers generally force the programmer to be a bit more aware of this.

While I think about it, a good next step for this PR would be to carefully go through the types and mark anything not explicitly designed as an extension point as `sealed`.

A good heuristic for when something should be sealed is if none of its methods are abstract or virtual.

**Comment by varon** [comment]
Opened a separate issue for the above comment - #566

**Comment by Nihlus** [comment]
@varon I believe that marking types as sealed should be done as a separate PR so that we don't mix effective changes. It's also a lot more involved than this (and a number of other modernizing PRs which are in the pipe), since it requires manual labor while these have been done through ReSharper.

**Pull request merged**
