### PR TITLE
Add Quaternion to Euler angles conversion

### PR DESCRIPTION
**Pull request by NogginBops**
### Purpose of this PR

Currently there exist methods for creating Quaterions from Euler angles but there are no methods that do the inverse.

What I aim to do is add a consistent (rotation order) way to extract Euler angles and have that be then without too much accuracy loss be converted in to a as much as possible equal Quaternion that created the Euler angles. But as this conversion is lossy it will not always be possible.

API example:
```cs
public Vector3 ToEulerAngles(Quaternion q);
```

### Testing status

Testing should include verification that the conversion is mostly lossless except in the cases where the Quaternion starts to approach the singularities that exist in the conversion (north and south poles).

### Comments

The reason one would want these methods is to implement a inspector similar to those found in most modern game engine editors.

### CODE REVIEW

**Comment by varon** [comment]
This is a good PR, would love to see it in. Don't forget to remove the [WIP] in the title when you're ready for a review!

**Comment by NogginBops** [comment]
Yes, I'm going to push a change with some tests to confirm that the math is as correct as possible. Should hopefully be able to do that later today.

**Comment by varon** [comment]
Just chasing up on this, anything I can do to help get this in?

Syntax error on the tests on travis.

>QuaternionTests.fs(50,48): error FS0256: A value must be mutable in order to mutate the contents or take the address of a value type, e.g. 'let mutable x = ...' [/home/travis/build/opentk/opentk/tests/OpenToolkit.Tests/OpenToolkit.Tests.fsproj]```

**Comment by varon** [comment]
@NogginBops  - Happy to merge as we discussed in Discord, just needs a fix up and for travis-CI to pass!

**Comment by varon** [comment]
Excellent work. Thanks again @NogginBops !

**Pull request merged**
