### PR TITLE
[WIP] Added DocFX project

### PR DESCRIPTION
**Pull request by djohns451**
### Purpose of this PR

* Documentation is now built with DocFX, writing to the docs directory.
* Affects all documented areas.
* Currently live [on fork github.io site](https://djohns451.github.io/opentk/index.html)

### Testing status

* Manual testing currently is handled with a `docfx.exe docfx_project/docfx.json --build`.
* Process can be automated with CI without any currently foreseen issues.

### Comments

* Documentation is served via Github's `<Project>`.github.io facilities, therefore it is subject to the same downtime as any other project that is.

### CODE REVIEW

**Comment by wcdeich4** [comment]
@Frassle @daerogami @varon What do you guys think?

**Comment by daerogami** [comment]
Spoke with @djohns451 very briefly in gitter. I'm working on porting the old manual to gitbooks. I'm interested to see what DocFX has to offer in comparison. I'm not particularly impressed with GitBooks flat ToC nor the editor, but those are small issues since it's essentially the same Jekyll-based site that gitpages are running (as far as I can tell).

I say we let both of these take shape then make a more informed decision from there.

**Comment by Nihlus** [comment]
Any modern IDE has extensive inline code completion and documentation previews. However, it's not a bad thing to have an online mirror for out-of-program reference.

**Comment by tzachshabtay** [comment]
Actually, the intellisense experience in both Visual Studio and other IDEs is incomplete. Several of the xml tags in the comments are ignored (even if you browse using the object explorer), like code examples and "seealso" tags. In DocFX those are not ignored, here's an example of a code sample from my engine (too bad they don't show syntax highlighting, though): https://tzachshabtay.github.io/MonoAGS/api/AGS.API.IWalkComponent.html#AGS_API_IWalkComponent_WalkAsync_AGS_API_ILocation_

Also DocFX creates automatic links for related items (you can also see that in the example above), which makes it much easier to navigate and get to know an API.

**Comment by djohns451** [comment]
@Nihlus, @tzachshabtay, @wcdeich4, @daerogami, what else would you all like to see from this?

**Comment by tzachshabtay** [comment]
https://www.divio.com/en/blog/documentation/?utm_source=programmingdigest&utm_medium=email&utm_campaign=featured

So the API reference is 1-out-of-4, and missing are tutorials, how-tos and explanations.

**Comment by Nihlus** [comment]
Thank you for you contribution! Currently, the `develop` branch is frozen while we work on the 4.0 release, and we are not accepting pull requests to it. All current pull requests should be based on that branch, or should be updated to be based on it.

In order to avoid clutter in our pull requests, we're going to be closing any pull request that isn't targeting 4.0 on the 31st of July, 2018. Please rebase your pull request before then.

**Pull request closed without merging**
