### PR TITLE
Bindings generator for modularity and ADL

### PR DESCRIPTION
**Pull request by Perksey**
## Purpose of this PR
This PR aims to refactor the bindings generator to write ADL interfaces and enums in a modular fashion, similar to the structure set in #805. 

## Comments
Discussions took place in #854 to decide whether ADL should be used for all subsystems. This PR is in response to the collective decision to use ADL for everything, even OpenGL.

### CODE REVIEW

**Comment by Perksey** [comment]
# Overloading subchecklist
- [ ] ArrayParameterConvenienceOverloader
- [ ] IFunctionOverloader
- [ ] PointerParameterPermutationOverloader
- [ ] ReturnTypeConvenienceOverloader
- [ ] StaticCountParameterConvenienceOverloader
- [ ] VoidPointerParameterOverloader
- [ ] VoidPointerReturnValueOverloader

**Comment by Perksey** [comment]
@Nihlus @varon Ready for review. Not fully done yet, but the only things left to do is to add overloads and make everything StyleCop-compliant.

**Comment by varon** [comment]
Thanks! Will review soon as I get time!

**Comment by varon** [comment]
How are we looking here? Ready for that review?

**Comment by Perksey** [comment]
Yeah, go for it man! Pretty much everything is implemented, just a few overloaders to go now.

**Comment by Perksey** [comment]
@varon Review comments rectified :)

**Pull request merged**
