### PR TITLE
Allow using OpenGL ES3 with Angle and extract a Direct3D shared handle

### PR DESCRIPTION
**Pull request by l3m**
This is an updated version of my previous pull request  #230.

These changes improve interoperability of OpenTK with Angle as rendering backed. Specifically, it allows a user to render with OpenGL|ES3 into offscreen surfaces, and retrieve the Direct3D-shared handles (texture pointers) of those surfaces for interop with Wpf (Windows Presentation Foundation) Guis or other frameworks that use Direct3D.

I added ```GraphicsContextFlags``` that allow a user to request an Angle-backed context with different backends as well as an ```Offscreen``` flag. If an EglContext is created with ```Offscreen```, the default surface is a PbufferSurface, not a WindowSurface. 

I found the way that OpenTK currently deals with contexts a bit confusing, and tried to keep changes to existing classes minimal. 

Therefore, I created an ```AngleInterop``` class where some references for the contexts that use Angle are stored. This allows a user to request shared handles for interop purposes, create additional surfaces for offscreen rendering, and retrieve their pointers.

I am happy to update or restructure my code if someone knows a better way to achieve this. 

A demo using these changes can be found [here](https://github.com/l3m/wpf-gles).

2015-03-18 18_50_09-wpf gl_es demo

### CODE REVIEW

**Comment by l3m** [comment]
Do not merge - after understanding OpenTK platforms a bit better, I think I can rewrite the implementation to avoid the angle-specific registration and stuff and bring it more inline with other platforms (since there is no reason that Angle-support should be integrated only with windows).

**Comment by l3m** [comment]
I updated the prq to be much less intrusive. It also does no longer interfere in windows-platform specific stuff. Instead, I created an angle factory and use it where appropriate. 

A user would instantiate an AngleOffscreenRendering instance (similar to when using a GLControl). Resizing and getting a Direct3D texture pointer (shared handles) are handled over this AngleOffscreenRendering instance, and the GraphicsContext and WindowInfo instances are exposed on it, too. 

I also updated my wpf demo to use the latest version - I also added all dependencies there to the repo, so you can checkout and it should just work.

**Comment by Frassle** [comment]
Right starting a code review. 

> (since there is no reason that Angle-support should be integrated only with windows).

Well apart from the whole DirectX thing. Honestly if it's cleaner assuming it's Windows only we should do that.

Few things that aren't clear.

It's not clear how adding OPENGL_ES3_BIT is useful? Where's it being used? Also even if we add that I don't think the EGLContext should treat ES2 and ES3 as separate things, there the same dynamic library.

 The bugfix to handle when the shared context is really an IGraphicsContextInternal, seems to also of changed to assume it's never just an IGraphicsContext? I would of thought given the parameter is typed to be an IGraphicsContext that any IGraphicsContext should be valid... Can you explain this?

Angle-related enums and definitions looks ok.

In the final commit I don't see why we're trying to distinguish Angle as different from the embedded context? I don't want to see Angle as a different thing, I want Angle to be a way of presenting me an Egl/Gles context on Windows.

The PBuffer support in EglWindowInfo looks ok, but does result in the oddity that we've got an IWindowInfo that isn't really a window. I can't see this causing any issues but might want to mull about it.

In EglGraphicsMode I think SelectGraphicsMode backend_bit parameter should be renamed surface_type and changed to new Enum listing the allowed values [Section in the man pages describes the allowed values for SURFACE_TYPE](https://www.khronos.org/registry/egl/sdk/docs/man/html/eglChooseConfig.xhtml).

I see the need for EglAnglePlatformFactory but is it possible to implement the other methods there? I guess it can probably copy a lot of code from the Windows platform?

The offscreen rendering I'm really not sure about, it feels more complicated then needed but need to think on it some more, might need to expose offscreen rendering higher up maybe.

**Comment by l3m** [comment]
> Well apart from the whole DirectX thing. Honestly if it's cleaner assuming it's Windows only we should do that.

The angle team is adding an (non-es) OpenGL backend at the moment. The plan is that Angle can be used on Mac and Linux too, and will work as an OpenGL|ES to OpenGL layer. 

> It's not clear how adding OPENGL_ES3_BIT is useful? Where's it being used? Also even if we add that I don't think the EGLContext should treat ES2 and ES3 as separate things, there the same dynamic library.

Ok, I will remove this.

> The bugfix to handle when the shared context is really an IGraphicsContextInternal, seems to also of changed to assume it's never just an IGraphicsContext? I would of thought given the parameter is typed to be an IGraphicsContext that any IGraphicsContext should be valid... Can you explain this?

I can do it for both. I assumed (maybe wrongly) that behind the facade, the internal object would be used (because that's what OpenTK passed in when I used shared contexts via GLControl).

> In the final commit I don't see why we're trying to distinguish Angle as different from the embedded context? I don't want to see Angle as a different thing, I want Angle to be a way of presenting me an Egl/Gles context on Windows.

But it's not a windows-only thing - the roadmap angle presented [here](https://code.google.com/p/angleproject/wiki/Update20150105) clearly stated that they are focused on cross-platform and the OpenGL backend now. That's why I made it non-only-for-windows. 

> The PBuffer support in EglWindowInfo looks ok, but does result in the oddity that we've got an IWindowInfo that isn't really a window. I can't see this causing any issues but might want to mull about it.

Indeed. The problem is that the client needs some way to access some internals in order to get the shared handles. While I see that it's not perfect, I feel this way is much nicer and clearer now, since the user has the instance to the object where he can call the QuerySurfacePointer instead of calling some  static methods hidden inside EGL. 

> In EglGraphicsMode I think SelectGraphicsMode backend_bit parameter should be renamed surface_type and changed to new Enum listing the allowed values Section in the man pages describes the allowed values for SURFACE_TYPE.

Ok, will do that. 

> I see the need for EglAnglePlatformFactory but is it possible to implement the other methods there? I guess it can probably copy a lot of code from the Windows platform?

Yeah, but again, I would prefer to not have it be dependent on Windows. I will do it if you want, but .. well, I would rather not :)

> The offscreen rendering I'm really not sure about, it feels more complicated then needed but need to think on it some more, might need to expose offscreen rendering higher up maybe.

I think the main problem is that the calls for creating/resizing the pbuffer surfaces need display and surface pointers. Those are not exposed in non-offscreen modes. And I would assume that it is a common use case is to have a single context but multiple offscreen buffers; at least that's what we require. 

I thought about making an OffscreenBuffer class and expose this, but after doing a prototype it felt more complex than the current version. 

If you have a proposal on how to best approach this, I am happy to adapt my code.

**Comment by Frassle** [comment]
>> Well apart from the whole DirectX thing. Honestly if it's cleaner assuming it's Windows only we should do that.

> The angle team is adding an (non-es) OpenGL backend at the moment. The plan is that Angle can be used on Mac and Linux too, and will work as an OpenGL|ES to OpenGL layer.

Ah wasn't aware of that. Ok that changes some things.

>> In the final commit I don't see why we're trying to distinguish Angle as different from the embedded context? I don't want to see Angle as a different thing, I want Angle to be a way of presenting me an Egl/Gles context on Windows.

> But it's not a windows-only thing - the roadmap angle presented here clearly stated that they are focused on cross-platform and the OpenGL backend now. That's why I made it not-only-for-windows.

Right ok that complicates things somewhat. From the Windows perspective it made sense to have it just be the Egl implementation but I can see on Linux/Mac you might want to choose between native Egl and Angle. I'll think and get back to this.

>> The PBuffer support in EglWindowInfo looks ok, but does result in the oddity that we've got an IWindowInfo that isn't really a window. I can't see this causing any issues but might want to mull about it.

> Indeed. The problem is that the client needs some way to access some internals in order to get the shared handles. While I see that it's not perfect, I feel this way is much nicer and clearer now, since the user has the instance to the object where he can call the QuerySurfacePointer instead of calling some static methods hidden inside EGL.

Yeh I can't see a better way right now. Fine as it is but will keep thinking about it.

>> I see the need for EglAnglePlatformFactory but is it possible to implement the other methods there? I guess it can probably copy a lot of code from the Windows platform?

> Yeah, but again, I would prefer to not have it be dependent on Windows. I will do it if you want, but .. well, I would rather not :)

Hmm so maybe we want the Angle platform to have a reference to the real platform to forward those calls to?

>> The offscreen rendering I'm really not sure about, it feels more complicated then needed but need to think on it some more, might need to expose offscreen rendering higher up maybe.

> I think the main problem is that the calls for creating/resizing the pbuffer surfaces need display and surface pointers. Those are not exposed in non-offscreen modes. And I would assume that it is a common use case is to have a single context but multiple offscreen buffers; at least that's what we require.
> I thought about making an OffscreenBuffer class and expose this, but after doing a prototype it felt more complex than the current version.
> If you have a proposal on how to best approach this, I am happy to adapt my code.

I'm just wondering about how offscreen rendering looks if you just wanted to use like desktop GL on Windows. I know it's not trivial but might be nicer to expose in a more platform generic way if possible. I'll see what I can come up with.

**Comment by l3m** [comment]
> I'm just wondering about how offscreen rendering looks if you just wanted to use like desktop GL on Windows. I know it's not trivial but might be nicer to expose in a more platform generic way if possible. I'll see what I can come up with.

Ah, yes. I can do this, put back the Angle stuff. I just assumed that this is generally not so useful, since the D3D-Texture we get from offscreen rendering can be used in any framework, while GLControl is Winforms-only.

**Comment by l3m** [comment]
I changed some of the things you requested. 

Open are still: 

> ES2, ES3 

Treating ES2 and ES3 differently. Not sure - I think it's probably safer to have them separate. But if you disagree still, I will change that and merge the ES2/ES3 stuff. 

> Windows Platform

So I looked at it and I am not sure how to do this best. I see two solutions: 

- Taking the assumption that Embedded on Windows always means Angle. Not sure if that's a good thing to force, even if it's probably the reality for most people. 

- Adding yet another flag: GraphicsContextFlags.WindowsWithAngleBackend. 

What do you think?

**Comment by Frassle** [comment]
Thanks, quick look it's looking better. Lemme think about those other issues for a bit, probably a clean way of solving this.

**Pull request closed without merging**
