### PR TITLE
Updated Linux/KMS platform to work with recent versions of libinput / Fix for Linux/KMS rendering glitches

### PR DESCRIPTION
**Pull request by malcolmstill**
OpenTK crashes when attempting to use the Linux/KMS platform with recent (newer than circa 2014) versions of libinput. For example it crashes on Fedora 25. This pull request updates the bindings to use the updated libinput API.

### CODE REVIEW

**Comment by malcolmstill** [comment]
I am seeing rendering artefacts on Linux/KMS. This is running on Fedora 25 with an Intel graphics chip (Macbook Air 2012).

See [an example here](https://www.youtube.com/watch?v=INfpj87BZOM) of the issue. The code for that example is (slightly [modified version of this](https://gist.github.com/ashwin/5727049)) 
```
// C# example program to demonstrate OpenTK
//
// Steps:
// 1. Create an empty C# console application project in Visual Studio
// 2. Place OpenTK.dll in the directory of the C# source file
// 3. Add System.Drawing and OpenTK as References to the project
// 4. Paste this source code into the C# source file
// 5. Run. You should see a colored triangle. Press ESC to quit.
//
// Copyright (c) 2013 Ashwin Nanjappa
// Released under the MIT License

using System;
using OpenTK;
using OpenTK.Graphics;
using OpenTK.Graphics.OpenGL;
using OpenTK.Input;

namespace StarterKit
{
    class Game : GameWindow
    {
        float angle = 0.0f;

        public Game()
            : base(800, 600, GraphicsMode.Default, "OpenTK Quick Start Sample")
        {
            VSync = VSyncMode.On;
        }

        protected override void OnLoad(EventArgs e)
        {
            base.OnLoad(e);

            GL.ClearColor(0.1f, 0.2f, 0.5f, 0.0f);
            GL.Enable(EnableCap.DepthTest);
        }

        protected override void OnResize(EventArgs e)
        {
            base.OnResize(e);

            //GL.Viewport(ClientRectangle.X, ClientRectangle.Y, ClientRectangle.Width, ClientRectangle.Height);

            Matrix4 projection = Matrix4.CreatePerspectiveFieldOfView((float)Math.PI / 4, Width / (float)Height, 1.0f, 64.0f);
            GL.MatrixMode(MatrixMode.Projection);
            GL.LoadMatrix(ref projection);
        }

        protected override void OnUpdateFrame(FrameEventArgs e)
        {
            base.OnUpdateFrame(e);

            if (Keyboard[Key.Escape])
                Exit();
        }

        protected override void OnRenderFrame(FrameEventArgs e)
        {
            base.OnRenderFrame(e);

            GL.Clear(ClearBufferMask.ColorBufferBit | ClearBufferMask.DepthBufferBit);

            Matrix4 modelview = Matrix4.LookAt(Vector3.Zero, Vector3.UnitZ, Vector3.UnitY);
            GL.MatrixMode(MatrixMode.Modelview);
            GL.LoadMatrix(ref modelview);
            angle = (angle + 1.0f) % 360.0f;
            GL.Rotate(angle, 0.0f, 0.0f, 1.0f);

            GL.Begin(BeginMode.Triangles);

            GL.Color3(1.0f, 1.0f, 0.0f); GL.Vertex3(-2.0f, -2.0f, 4.0f);
            GL.Color3(1.0f, 0.0f, 0.0f); GL.Vertex3(2.0f, -2.0f, 4.0f);
            GL.Color3(0.2f, 0.9f, 1.0f); GL.Vertex3(0.0f, 2.0f, 4.0f);

            GL.End();

            SwapBuffers();
        }

        [STAThread]
        static void Main()
        {
            // The 'using' idiom guarantees proper resource cleanup.
            // We request 30 UpdateFrame events per second, and unlimited
            // RenderFrame events (as fast as the computer can handle).
            using (Game game = new Game())
            {
                game.Run(30.0);
            }
        }
    }
}
```

The issue I believe is in [src/OpenTK/Platform/Linux/LinuxGraphicsContext.cs](https://github.com/opentk/opentk/blob/develop/src/OpenTK/Platform/Linux/LinuxGraphicsContext.cs), specifically the `SwapBuffers method`:

```
        public override void SwapBuffers()
        {
            base.SwapBuffers();

            bo_next = LockSurface();
            int fb = GetFramebuffer(bo_next);

            if (is_flip_queued)
            {
                // Todo: if we don't wait for the page flip,
                // we drop all rendering buffers and get a crash
                // in Egl.SwapBuffers(). We need to fix that
                // before we can disable vsync.
                WaitFlip(true); // WaitFlip(SwapInterval > 0)
                if (is_flip_queued)
                {
                    Debug.Print("[KMS] Dropping frame");
                    return;
                }
            }

            QueueFlip(fb);
        }
```

The issue seems to be with the locking the surface before waiting for the page flip. By moving the LockSurface and GetFramebuffer after the wait, rendering appears as it should.

**Comment by varon** [comment]
@malcolmstill 
Apologies on taking so long to get around to reviewing this. Did you manage to catch those artifacts you were finding?

Beyond that, before I can merge we need to establish if these changes impact behaviour on any of the other platforms. Have you had a chance to test that?

**Comment by malcolmstill** [comment]
Yes, the PR fixes the glitches (in commit 3c71e9b).

If by platforms you mean does it affect platforms other than Linux/KMS, then no it only touches files used by Linux/KMS.

If by platforms you mean other graphics chips, I don't have hardware to test the glitch fix on anything other than Intel graphics chips.

**Comment by varon** [comment]
@Nihlus  - If you can check and merge this in, that would be awesome.

**Comment by Nihlus** [comment]
@malcolmstill I've gone over the changes, and it all looks fine. It would seem the Fixed24 structure has been rendered obsolete by this change as well - I see no reason to keep it. If you would remove it and rebase onto develop I'd consider this PR ready to move into freeze & final test before merging it in.

**Comment by malcolmstill** [comment]
@Nihlus can you push me in the right direction for rebasing, not entirely sure what to do?

If I run
```
git fetch upstream
git pull --rebase upstream develop
```

I get
```
From github.com:opentk/opentk
 * branch              develop    -> FETCH_HEAD
First, rewinding head to replay your work on top of it...
Applying: libinput v0.4 removed libinput_udev_create_for_seat and replaced with two functions libinput_udev_create_context and libinput_udev_assign_seat to separately create a context and assign it a seat name.
Applying: libinput v0.8 removed libinput_event_pointer_get_axis and replace with libinput_event_pointer_has_axis and libinput_event_pointer_get_axis_value now takes a specified PointerAxis
Applying: Pointer coordinate query functions now return doubles.
Applying: Removed @ symbol from IntPtr name
Applying: Use new Libinput.CreateContext and Libinput.AssignSeat functions in Setup().
Applying: Use new axis querying functions to update mouse scroll state.
Applying: Relative pointer motion should use the relative (Delta) query functions.
Applying: Mistake in change. The Debug.Print statement should not be there.
Applying: Some casts required in the absolute motion handler now that the query functions return doubles.
Applying: Moving the LockSurface after waiting for the page flip stops the rendering glitches on Linux/KMS.
Applying: Remove DRM cursor on Dispose.
Applying: Remove Fixed24 struct
```

When I then run 
```
git push origin develop
```

I get
```
To github.com:malcolmstill/opentk.git
 ! [rejected]          develop -> develop (non-fast-forward)
error: failed to push some refs to 'git@github.com:malcolmstill/opentk.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

I believe I can run `git push -f origin develop` but I'm not sure that's the correct thing to do.

**Comment by varon** [comment]
Just run `git pull origin develop` from your current branch

**Comment by varon** [comment]
This is hilarious. I have no idea how this happened. Let me see if I can do some git wizardry and open up a clean PR for you.

**Comment by varon** [comment]
@malcolmstill - No idea what you did to get that to happen, but I was able to recover just your changes and push out a separate PR for them. I've created a clean new PR here at #541 for you. Will leave this open for reference for now.

**Comment by Nihlus** [comment]
@malcolmstill Rebasing was, perhaps, the wrong term to use - when dealing with an already pushed changeset, merging with the intended branch is better than rebasing and not as prone to issues. It's been a while since I saw something blow up quite this spectacularly, though :joy:

**Pull request merged**
