### PR TITLE
[WIP] Support Joystick.Name

### LINKED ISSUE #312: Surface the joystick name as reported by the hardware.
Currently the only string identifier available for joystick devices is the Description property, which is just "Joystick/Joystick # (# Axes, # Buttons)". This isn't terribly useful to uniquely identify multiple joysticks in, say, an input config menu, and is name-collision prone for different devices.

### PR DESCRIPTION
**Pull request by Frassle**
Fixes #312

### Purpose of this PR

* Exposes joystick names through Joystick.GetName(int index)

### Testing status

* Nil :disappointed: 
* I don't have a gamepad or joystick to verify this but it's merely exposing existing variables publicly 

### Comments

* If anyone has some gamepads and joysticks they could test this with that would be grand!

### CODE REVIEW

**Comment by winterhell** [comment]
With an Xbox 360 controller I get "XInput Controller", with my 6 button pad I get "Unmapped Controller" which is the same text as for unavailable devices.

**Comment by Frassle** [comment]
Thanks for the test. Will look into it some more. Also wonder if better to expose this as just another field on joystick capabilities rather than a whole new method?

**Comment by leezer3** [comment]
I agree that this should be a field in Joystick capabilities, and probably read once at startup and then cached.

I did mess with this a while back, IIRC to get a nicely readable human-name on the Windows HID backend, you need to query the registry key for the VID / PID of the pad in question.
https://stackoverflow.com/posts/2223452/

Never got round to investigating the Linux etc. side of things, so shelved it.

**Comment by Frassle** [comment]
Yup looks like this will be more involved than simply forwarding what we call "name" currently. I'll rework to expose it as part of capabilities then will need some help to get this right.

**Comment by leezer3** [comment]
Whelp, last link was broken.

https://stackoverflow.com/questions/2208722/how-to-get-friendly-device-name-from-dev-broadcast-deviceinterface-and-device-in/2223452#2223452

Some further discussion in there, but that method definitely produced results when played with. Whether it's the best I don't know, sorry.

A later post on there seems to suggest that it's also present in the device broadcast notification, which I think the HID driver uses. but this is really not my field.

**Comment by varon** [comment]
@Frassle - could we add [WIP] to the title if you're still working on this?

**Comment by Nihlus** [comment]
Thank you for you contribution! Currently, the `develop` branch is frozen while we work on the 4.0 release, and we are not accepting pull requests to it. All current pull requests should be based on that branch, or should be updated to be based on it.

In order to avoid clutter in our pull requests, we're going to be closing any pull request that isn't targeting 4.0 on the 31st of July, 2018. Please rebase your pull request before then.

**Pull request closed without merging**
