### PR TITLE
Add xunit example

### PR DESCRIPTION
**Pull request by LaylConway**
For #232

### CODE REVIEW

**Comment by LaylConway** [comment]
I think the travis build failing has something to do with me creating the new tests project in VS 2015, I'll try to fix it.

**Comment by LaylConway** [comment]
Leaving this here for now to continue on it later, if someone knows a way to fix the build I'll update this pull request with it.

**Comment by xanather** [comment]
https://github.com/xunit/xunit/issues/91 looks related

**Comment by LaylConway** [comment]
Following the trail, it seems we're waiting on https://github.com/mono/mono/pull/1654 before this will run.

**Comment by Frassle** [comment]
Ugh that is annoying :( I don't see any workarounds on those threads either?

So we're down to waiting or trying a different test system?

**Comment by LaylConway** [comment]
Only workaround for now would probably be pulling from the pull request repo and building. I don't know any estimates on how long it will take for this to get on travis' latest mono.

**Comment by Frassle** [comment]
Hmm ok. Well if we go with this will get fixed on travis eventually and xUnit2 is the latest and greatest framework to use I think it would be a good idea to continue working on getting xUnit2 to build and run locally and I'll open an issue to add it to travis when we can.

**Comment by LaylConway** [comment]
This pull request will already build and run locally, I could revert the changes on .travis.yml so it won't fail in travis anymore.

**Comment by Frassle** [comment]
Sounds good, I'll give it a test locally when I've got a chance. I'm bringing up an Ubuntu box at some point so can try it out on MonoDevelop as well.

**Comment by daerogami** [comment]
Recommend reviewing this pull request since [mono/mono#1654](https://github.com/mono/mono/pull/1654) has been merged; however, current unit-testing is moving towards the direction of NUnit. This pull request may be obsolete; however, xUnit tests should be maintained for reference/future use.

**Comment by cra0zy** [comment]
@daerogami Please stop going around PRs saying "Reccomend this" "Don't recommend this", it's not helping whatsoever.

**Comment by wcdeich4** [comment]
@daerogami when I said to try to bring chaotically dispersed OpenTK, I meant googling for how there are websites not connected to github.com/opentk or opentk.com that have OpenTK code samples - but @daerogami thanks for your enthusiasm & reviewing the old merge requests.

**Comment by varon** [comment]
This should be covered by the new build system. Closing.

**Pull request closed without merging**
