### PR TITLE
Adds casting from one VectorX to another VectorX

### PR DESCRIPTION
**Pull request by imkSushi**
### Purpose of this PR

Adds casting from one VectorX to another VectorX

### Testing status

Code is fairly trivial.

### Comments

Not sure whether non-lossy casting should be implicit or explicit, e.g. Vector2i -> Vector2, as int -> float is implicit.

### CODE REVIEW

**Comment by imkSushi** [comment]
Currently, my implicit vs explicit has the philosophy that if it is lossy, it should be explicit, if it is non-lossy, implicit, hence:
(f - VectorX; d - VectorXd; h - VectorXh; i - VectorXi)
f->d: implicit
f->h: explicit
f->i: explicit
d->f: explicit
d->h: explicit
d->i: explicit
h->f: implicit
h->d: implicit
h->i: explicit
i->f: implicit
i->d: implicit
i->h: explicit - this is lossy as Half doesn't support numbers larger than about 2^16

**Comment by imkSushi** [comment]
I should probably also add casting for Matrices, Boxes and Quaternions, but I'd rather get a definitive answer on implicit vs explicit first.

**Comment by varon** [comment]
Seems like this slipped under the radar.  Totally agree with all of this. Don't worry about matrices/box/quaternions for now.

**Review by varon — APPROVED** [review]

**Comment by varon** [comment]
All good to merge, but we need to resolve the conflict. Thanks again for this contribution.

**Comment by varon** [comment]
Sorted. Thanks again!

**Pull request merged**
