### PR TITLE
Vector transform operators see #329

### PR DESCRIPTION
**Pull request by MatthiasHarvey**
#329

### CODE REVIEW

**Comment by wcdeich4** [comment]
Hi. Would be willing to consider having 2 different versions of the matrix * vector operators?  As you probably know matrix multiplication is "associative but not commutative" meaning vector * Matrix != Matrix * vector. 

Example: Your operator **public static Vector3 operator *(Matrix3 mat, Vector3 vec)** has the vector on the right hand side, but it calls **Vector3.Transform(ref vec, ref mat, out result)** which is actually a left handed vector-matrix multiplication.

As a math specialist, I would like to see the operator signature changed to **public static Vector3 operator *(Vector3 vec, Matrix3 mat)** and then have the **public static Vector3 operator *(Matrix3 mat, Vector3 vec)** call a new **Vector3.RightHandedTransform(ref vec, ref mat, out result)** method that does not exist yet...... 

What do you think?

**Comment by MatthiasHarvey** [comment]
Hi. I see what you are saying and I agree. I am not a math specialist myself (yet) so I appreciate the help.

How would **Vector3.RightHandedTransform(ref vec, ref mat, out result)** work?

**Comment by wcdeich4** [comment]
Hi :)   Well, the core of **Vector3.RightHandedTransform(ref vec, ref Matrix3 mat, out Vector3 result)** would look like this:

new OpenTK.Vector3(
                mat.Row0.X * V.X + mat.Row0.Y * V.Y + mat.Row0.Z * V.Z ,
                mat.Row1.X * V.X + mat.Row1.Y * V.Y + mat.Row1.Z * V.Z,
                mat.Row2.X * V.X + mat.Row2.Y * V.Y + mat.Row2.Z * V.Z );


And for Matrix4 X Vector3 I would do a "homogenous" transform.  "Homogenous" means you assume the 4th value of the vector is 1 even though there are only 3 values in that vector  (X,Y,Z).  This is very useful for "translations" where you want the point to shifted up/down and/or left/right and/or forward/backward.

**Vector3.RightHandedTransform(ref vec, ref Matrix4 mat, out Vector3 result)**

new OpenTK.Vector3(
                mat.Row0.X * V.X + mat.Row0.Y * V.Y + mat.Row0.Z * V.Z + mat.Row0.W,
                mat.Row1.X * V.X + mat.Row1.Y * V.Y + mat.Row1.Z * V.Z + mat.Row1.W,
                mat.Row2.X * V.X + mat.Row2.Y * V.Y + mat.Row2.Z * V.Z + mat.Row2.W);



Basically the operators you already made are 100% perfect if you just swap the order of the parameters so it's vector X matrix.    For matrix X vector you should do something like the 2 examples above **(for Matrix4 X Vector4 mat.RowN.W would be multiplied by the 4th value of the vector, V.H I believe it is called).**


Now if you want, you can just swap the order of the parameters in the operators you made & I can make the right-handed versions later --- or if you want the practice you can make them all.  I do have other things to work on, so if you want to make them all, I won't stop you :)

Sorry I didn't introduce myself sooner.  My name's William.  I'm one of the new OpenTK maintainers since Frassel left.

BTW, just as a side note, nearly all engineers, mathematicians, physicists, etc use a "right handed coordinate system" & multiply a matrix by vector on the right hand side.  Also most other graphics packages like DirectX do it that way.  I'm guessing OpenGL got stuck w/ left handed vector X matrix multiplication b/c that can save on memory space in computation if you do it a certain way & that may have been more important in the 80s when memory space was at a premium.  

The good news is C# operators let you specify which side of the symbol the parameter will be by the order of the parameters in the operator method signature, so we can support doing it both ways :)

**Comment by MatthiasHarvey** [comment]
Hi William :)

Great, thanks for all your effort! I will swap the order on the functions I made and I'll also try making the right-handed versions.

**Comment by MatthiasHarvey** [comment]
I've made the changes and added the other functions. Can you please check if this is okay?

**Comment by wcdeich4** [comment]
Looks great :)

**Comment by cra0zy** [comment]
@wcdeich4 You shouldn't have merged this, the spaces/tabs are messed up. From now on, lets make it required for both of us to say something passes for something to be merged.

Other reason(and correct me if I am wrong) is you guys decided to do something weird, you decided that:
```
public static Vector3 Transform(Vector3 vec, Matrix3 mat)
public static Vector3 RightHandedTransform(Vector3 vec, Matrix3 mat)
```

is better than:
```
public static Vector3 Transform(Vector3 vec, Matrix3 mat)
public static Vector3 Transform(Matrix3 mat, Vector3 vec)
```
that is you created a new method for something that could have been done with the existing method.

**Comment by cra0zy** [comment]
Stuff fixed with https://github.com/opentk/opentk/commit/3d58a0b50a3b9c32cf97abc1e345b1b51c0384ad

@wcdeich4 Please be careful what you do.

**Comment by cra0zy** [comment]
> Since it was just committed it, we could change RightHandedTransform(Vector3 vec, Matrix3 mat) to just Transform(Vector3 vec, Matrix3 mat) & C# will call the correct method based the parameter order. Would you like to do that?

I already did it... https://github.com/opentk/opentk/commit/3d58a0b50a3b9c32cf97abc1e345b1b51c0384ad

> You bring up a good point. What should be the procedure for approving merge requests?

Lets just say 2 maintainers have to agree that the PR should get merged.

**Comment by amulware** [comment]
I'm ok with that rule as well. I would also add that we always should wait at least a few days to make sure all of us (and others) can weigh in, in case we can find something problematic with the PR.

**Comment by amulware** [comment]
Speaking of which, I do NOT agree that the Transform(RightHanded) methods taking a Matrix4 should do a homogenous transformation.

The reason being that there are already TransformPosition() methods, which do this. If those are kept (and I think they should be), all Transform() methods should ignore the last row of the Matrix4 I think.

I also think that we should not have Matrix4 * Vector3 operators (or the other way around) since this is ambiguous.
If the user wants to work with homogenous coordinates, I think they should use Vector4 instead, or call the appropriate Transform(Position) methods, so that their code is clear.

Overall, I think it is really important that we make it as difficult as possible to get things wrong for users of the library.

**Comment by cra0zy** [comment]
> I would also add that we always should wait at least a few days to make sure all of us (and others) can weigh in, in case we can find something problematic with the PR.

I agree.

**Comment by wcdeich4** [comment]
@amulware the homogenous transform allows for rotation/scale + position in 1 matrix & they do ignore the 4th row of the matrix.  Remember, in computer graphics, every millisecond counts when your trying to maintain the frame rate while doing calculations - that's why multiplying a Matrix4 by a Vector3 once is much more efficient than multiplying by a Matrix3 then calling the TransformPosition() method.

**Comment by amulware** [comment]
I understand what a homogenous transformation is. However, I would ask you to look at the TransformPosition() method. It already takes a Matrix4 and does exactly the calculations you want to do in the Transform() method. In fact, the way it is implemented right now, by creating a Vector4 (with w=1) and calling Vector4.Transform(), it may be slower than the existing TransformPosition (which does the same thing).

I also understand the need for performance, and I would be one of the first to argue for its importance. However, since we want others to use OpenTK, we should make it as easy to use and as little confusing as possible. Currently we have:
```
Transform(V3, M3) -> non homogeneous

Transform(V3, M4) -> homogeneous
TransformPosition(V3, M4) -> homogeneous
```
I argue that this is inconsistent and that there is no reason to have the M4 overload of Transform() since TransformPosition() does the exact same thing, and is much clearer about it (since it is appropriately named).

If we want to have that overload, I argue that it should be non homogeneous to be consistent with the other methods of the same name:
```
Transform(V3, M3) -> non homogeneous
Transform(V3, M4) -> **non** homogeneous

TransformPosition(V3, M4) -> homogeneous
```

**Comment by wcdeich4** [comment]
@cra0zy & @amulware OK, let's go ahead & remove the homogenous multiplication operators quick before anyone starts using them as part of the API.  One of you want to do it, or should I remove them?

@amulware I understand what you're saying about confusion, that's why I thought it might be good to have a function name like "RightHandedTransform" to clarify.  Granted it's a little weird b/c we don't have a "LeftHandedTransform" function, but pretty much all of the transforms already there are done left handed, so that could be understood w/ a few comment updates.

**Comment by wcdeich4** [comment]
@amulware Hi, I was just reviewing the code since no one has deleted it yet.  In the current version of the code:

_For Matrix4 * Vector3 (right handed)_
 **Vector3 operator *(Matrix4 mat, Vector3 vec)** line 1619 of Vector3.cs, calls **void Transform(ref Matrix4 mat, ref Vector3 vec, out Vector3 result)** line 1230 of Vector.cs..
No Vector4 is created. 

_For Vector3 * Matrix4 (left  handed)_
**Vector3 operator *(Vector3 vec, Matrix4 mat) ** line 1592 Vector3.cs calls **void Transform(ref Vector3 vec, ref Matrix4 mat, out Vector3 result)** line 155 Vector3.cs which does create a Vector4 struct & calls **void Transform(ref Vector4 vec, ref Matrix4 mat, out Vector4 result)** line 983 Vector4.cs

Both of these are  homogenous, it's just Transform(V3, M4)  does it "formally" by creating a new Vector4 structure so it can call the existing Transform(V4, M4) on line 983 of Vector4.cs

Now there are two versions of TransformPosition(...) in Vector3.cs.  Both multiply a Vector3 * Matrix4 (left handed multiplication only - there is  no).

Now I did  not write this code myself.  The  new code was written by @MatthiasHarvey & it was refactored by @cra0zy to fix the tab indents, regularize the names..., but from my perspective the M4 * V3 operator is efficient, clear & mathematically correct.  The V3 * M4 operator is mathematically correct & only slightly less efficient.

So @amulware before anyone deletes this, could you explain again why these homogenous operators are too confusing to keep?  --- if your only concern is lack of efficiency due to creating a Vector4 structure which eventually gets thrown away for the V3 * M4 operator, we could just change the **Vector3 operator *(Vector3 vec, Matrix4 mat)**  to call **void TransformPosition(ref Vector3 pos, ref Matrix4 mat, out Vector3 result)** on line 1099 of Vector3.cs 

Also, while C# allows for "extension methods" where you can basically tack on methods that a class / structure did not previously have --- an extension method cannot be an operator.  So if we remove these operators, it will be impossible for users to have a Matrix4 * Vector3 operator

**Comment by wcdeich4** [comment]
BTW,  just as a footnote, it is odd that **public static Vector3 TransformPosition(Vector3 pos, Matrix4 mat)** line 1086 of Vector3.cs & **void TransformPosition(ref Vector3 pos, ref Matrix4 mat, out Vector3 result)** line 1099 of Vector3.cs do the same thing, only differently & the one on line 1086 is much less efficient b/c it creates 3 new Vector3 structures which are used then thrown away.

Now all over the code, there are examples where there is a _vector Transform(vector, matrix)_ function & another _void Transform(ref vector, ref matrix, out vector) _function, but the function that returns a vector actually calls the void function which has the out  parameter --- I don't know why TransformPosition functions are different. My guess is this is old code that has been there a long time & no one scrutinized it. This might be a little off topic, but if we're worried about efficiency, we should probably make **public static Vector3 TransformPosition(Vector3 pos, Matrix4 mat)** line 1086 of Vector3.cs call **void TransformPosition(ref Vector3 pos, ref Matrix4 mat, out Vector3 result)** line 1099 of Vector3.cs

**Comment by amulware** [comment]
If we are concerned about performance, we should profile it before we make any changes, based on small things like that. It might very well be that the compiler is smart enough to end up with the same code no matter wow exactly it is expressed here.

That being said, I agree that one of the two methods should call the other, just like with the other implementations.


About your earlier comment:

> could you explain again why these homogenous operators are too confusing to keep?

I do not think they are too confusing to keep, but I think they should NOT be homogeneous. None of the other methods called `Transform` are, so I think it is confusing to have a method of the same name that does something different 'just' because you pass a differently sized matrix.

In addition, `TransformPosition` already does exactly the same thing (and I really do not care about the implementation or efficiency at this point, I care about the interface we expose to our users), so having a second method with a different name, that has the same behaviour seems crazy to me.

I also do not thing that there should be M4*V3 or V3*M4 operators. The reason being that this is not a well defined operation, and there are two **valid** interpretations. That is why there should be two methods to tackle both cases: TransformPosition (homogeneous) and Transform (non homogeneous).

If this is not clear, I can make a pull request with the changes the way I think they should be.

---

Btw: I only just now saw that we also already have a `TransformVector(V3, M4)` method. So as far as I can tell, there really is no need for any vector3 + matrix4 transformations. They are all already present (including the more complicated one of `TransformNormal`).

**Comment by varon** [comment]
@amulware You're 100% correct here. When discussing the PR, it initially never included the operators for the same reasons. I would strongly argue for V3*M4 being a type error, rather than the OpenTK community having a long debate about whether it should be homogeneous or not.

Creating it would basically be be a special-case of an implicit conversion from Vec3 to Vec4.

**Comment by cra0zy** [comment]
> I can make a pull request with the changes the way I think they should be.

Do it.

**Comment by wcdeich4** [comment]
In math M4 * V3 and V3 * M4 are clearly defined & @thefiddler wanted more math operators which is why @MatthiasHarvey made this PR.

@amulware wrote "Btw: I only just now saw that we also already have a  TransformVector(V3, M4)  method. So as far as I can tell, there really is no need for any vector3 + matrix4 transformations"  - that already was a homogenous transform & it's left handed, so we should probably have a corresponding right  handed version (call it TransformPosition(M4,V3) or whatever you want) 

@varon V3*M4 (left  handed multiplication) is actually how the pre-existing Transform functions work

**Comment by amulware** [comment]
Can you provide a source for the mathematical definition of m4 * v3? I am not aware of such a thing.

**Comment by wcdeich4** [comment]
graphics.ucsd.edu/courses/cse167_f05/CSE167_03.ppt  slide 11, but you can save computations if you always take the W of the vector to be 1

**Comment by amulware** [comment]
The slide you reference shows a multiplication of a homogeneous vector (vector 4 with w=1, or a vector3 with the semantic meaning of being a position) with a matrix. I do not see how the Vector3 type is the same as a Vector4 type with w=1. Since Vector3 can be used to represent both positions and vectors, an operator V3 * M4 would be ambiguous.

I do not think that that ambiguity is just subjective. So, unless we can find a way to remove it, adding the operator is bound to cause at best confusion and uncertainty - and at worst bugs.

If you disagree with this, please explain why. Also maybe answer this question:

Why should V3*M4 do the same as `TransformPosition` (rotate and translate), and NOT the same as `TransformVector` (rotate)?

**Comment by wcdeich4** [comment]
@amulware I just realized it was my "Data Structures in Computer Graphics" professor not one of the pure math professors who introduced me the idea of "just assume vector.W is 1".  He would probably say "If you made the Matrix4 you should know what it's going to do to the vector/position" - but @amulware  you bring up a good point since OpenTK is a package that other people use, not something you write & only use yourself, so we do have to be extra careful understand what they're getting.

**Comment by wcdeich4** [comment]
@amulware thanks for the good math discussion

**Comment by amulware** [comment]
@wcdeich4 Agreed, and good.

I also agree with your earlier point, that there should be right handed operations for all the left handed ones. (Where it makes sense. Not sure if there are cases where it does not right now.) I'll see about making some time for this in the coming days.

There is also a bunch of operations which I think are entirely missing (V2 * M2 for example).

I'll try to get an overview of all of that, and add as much of the missing stuff as I can find.

**Comment by wcdeich4** [comment]
@amulware Thank you for your hard work :)   I've started an NUnitTests project for OpenTK but I may be working overtime this weekend, so may not get much added this week... 

@MatthiasHarvey Now that we know which operators we will support (Vn * Mn ad Mn * Vn) & how the functions will be named (see above), if you want you can go thru & make a Pull Request for the other vector classes (like Vector4d for double precision floating point numbers).  Also @MatthiasHarvey can you adjust the tab settings in your Visual Studio back to the default settings?

**Comment by MatthiasHarvey** [comment]
Hi. Sorry about the late reply. Glad everything is sorted out now.

@wcdeich4 I will try to add the functionality to the other classes, and I have changed my tab settings - sorry about that as well, I did not realise my settings were messed up.

**Pull request merged**
