### PR TITLE
Begin work on merging OpenAL extensions.

### PR DESCRIPTION
**Pull request by utkumaden**
### Purpose of this PR

* Merge all OpenAL extensions into a single assembly.

### Testing status
* None

### Comments
* As requested by @varon.

### CODE REVIEW

**Comment by utkumaden** [comment]
It seems I broke the solution file. I will restore to the original file, and then retry.

**Comment by utkumaden** [comment]
I think the PR is ready for review, however a 3rd party should examine the final difference carefully. I hope no mistakes were made.

**Comment by PJB3005** [comment]
Right now you're just merging all the project files into one, but you didn't touch any of the tiny enums/overloads created specifically to overcome the issue of "can't add to an enum from another assembly".

There should really only be one `IAL` class containing ALL the extension methods, and no overloads such as `IVorbisFormat.BufferData` which exist only to take `VorbisBufferFormat` which can just be merged with regular `BufferFormat`.

**Comment by varon** [comment]
@utkumaden  - Any luck/progress with this? Would be super to get this in for 4.0.

**Comment by utkumaden** [comment]
Sorry I haven't had much time to work on this. My finals are due so I won't have much time to work on it either. Looks like this is going to ship for a minor version.

**Comment by varon** [comment]
Merged at @NogginBops 's Request.

**Pull request merged**
