### PR TITLE
[4.0] Adding Lerp function in the math helper

### LINKED ISSUE #892: Math Lerp function missing
This function missing in MathHelper.cs
```csharp
return a + c * (b - a);
```

### PR DESCRIPTION
**Pull request by Pandav0x**
### Purpose of this PR

This PR aims to add the linear interpolation (LERP) function in the MathHelper class. (Closes #892)

### Testing status

Tests haven't been written yet.

### CODE REVIEW

**Comment by Perksey** [comment]
(Closes #892)

Also you don't need to write tests at this stage.

**Comment by Pandav0x** [comment]
Should I add an `ArgumentOutOfRangeException` if `t` is less than 0 or greater than 1 ?

**Comment by Perksey** [comment]
That's probably best given that this is the imprecise method.

**Comment by varon** [comment]
Just to chip in here:
Throwing an exception at runtime stops this from being a total function. It's probably better to just clamp `t` to `[0;1]`.

Automatic clamping is very convenient. Unity's `Mathf.Lerp` function operates this way as well.

**Comment by Pandav0x** [comment]
Thank you very much, I've clamped `t` to `[0;1]` instead of throwing an error.

**Comment by Perksey** [comment]
If that's all, remove the WIP mark and I'll merge :)

**Comment by Pandav0x** [comment]
Thank you :)

**Comment by varon** [comment]
Thanks @Pandav0x .

Every little bit counts. Well done, and we hope to see loads more in the future!

**Pull request merged**
