### PR TITLE
Remove code marked obsolete

### PR DESCRIPTION
**Pull request by Nihlus**
This PR removes almost all code that has been marked as obsolete in the current codebase. None of the removed obsolete code was in active use or ended in a non-obsolete access point save for one.

Obsolete code which was marked as such during the current development cycle was not altered or removed.

Summary of changes:
- Removal of code that had been marked [Obsolete]. This includes some GL bindings which were not automatically generated, but had been kept for compatibility purposes.
- Removed GameWindow::Keyboard and GameWindow::Mouse. These properties accessed obsolete code which was removed, but were not obsolete themselves by way of warning suppression. This is the only breaking change without prior notice.

### CODE REVIEW

**Comment by tzachshabtay** [comment]
I wish you'd reconsider keeping GameWindow.Mouse.
The alternative, as I understand, returns position in screen coordinates and not in window coordinates which is not what I (and I assume, most people) need.

**Comment by Nihlus** [comment]
@tzachshabtay Unfortunately, those properties rely on the old and obsolete input drivers. Getting window coordinates depend on the windowing toolkit in use, but I'm sure we can implement an alternative.

**Comment by Nihlus** [comment]
@tzachshabtay In the meantime, here's a fairly simple workaround:

```cs
System.Drawing.Point windowLocation = window.Location;
int mouseX = Mouse.GetCursorState().X;
int mouseY = Mouse.GetCursorState().Y;

int windowRelativeX = MathHelper.Clamp(mouseX - windowLocation.X, 0, window.Width);
int windowRelativeY = MathHelper.Clamp(mouseY - windowLocation.Y, 0, window.Height);

Console.WriteLine($"New mouse API (relative): {windowRelativeX}, {windowRelativeY}");
```

**Comment by Nihlus** [comment]
@varon We'll need to hold off on this for a little while. I found an issue with the current mouse implementation wherein it doesn't clamp its values to the actual screen size, so if you hit an edge and keep moving, the values will still increase or decrease depending on the edge. Useful for fullscreen games, but absolutely not intended behaviour.

**Comment by varon** [comment]
@Nihlus - Super busy at the moment, will check out the rest of the PRs etc. when I get some time next week or this weekend.

What do you think about just saying buggerit and dropping all non-SDL2 backends completely anyway? We can do a beta round for 3.0.0 this way.

**Comment by Nihlus** [comment]
@varon Dropping the non-SDL2 backends is a no go. We'll lose the ability to have GL widgets and controls that way, and that's too important for a lot of applications to drop. It's a bit too big of a change to do right now - something to look into after we've decomposed the library, I think. 

I've looked into the mouse issues more, and it's mainly a problem with some vagueness in the new mouse driver - it's the same problem on all platforms. I've ideas on a fix for it that should suffice, but it'll need a bit of time.

**Comment by varon** [comment]
Clarification - what I mean by dropping non-sdl backends is dropping the native backends. Just Linux/Windows/macOS.

**Comment by Nihlus** [comment]
Right, which will break embedded GL surfaces in most cases. 

If we drop the native backends, we'll have X11 and SDL2 left. While Windows and Mac can run X11, it's very uncommon and far more fiddly than the average user wants to deal with. This leaves SDL, which is very difficult to embed in any UI toolkits.

Dropping the MacOS backend, for instance, would restrict embedded GL to at most version 2.1 for xquartz users with an embedded widget, or force usage of an SDL window inside whatever toolkit you use. The latter is problematic for a number of reasons - double event loops, extra overhead, the fact that SDL was not designed for that sort of thing, etc. Similar problems will arise for Windows.

I really, really, don't think we should drop them - it would introduce far more problems than it would solve.

**Comment by leezer3** [comment]
Please don't drop the native backends.

Mixing SDL and Winforms is a massive headache at the best of times, and the native backend is far better at this. It gets even messier when non-Windows platforms are involved.

SDL on Mac is also a pain in the neck, as I've then got to point users at the appropriate framework and provide instructions on installing it properly. At the minute, it's a simple drag to the applications folder.
(I suppose I could probably script it, but I'd *really* rather not do that for all manner of reasons)

**Comment by varon** [comment]
@leezer3  - Our intention is to avoid the people having to write the same patch 4 times over for different systems, i.e. with #542.

We don't want to break any of the GLWidget or GLControls. Just the 'native windowing' stuff should be done with SDL2 instead. Having spoken with @Nihlus here, it's going to require some careful planning and community input, so we're not going to do that as part of this PR.

**Comment by leezer3** [comment]
I see your point, but in my eyes the (normally relatively minor) maintenance headache is IMHO preferable as it gives the end-user considerably more flexability.

An example of what I mean by mixing the SDL backend and Winforms:
Create a Winform with no widgets of any description, but which polls joysticks.
This works perfectly with the native backends, but SDL requires a gamewindow before it starts pumping events.

**Pull request merged**
