### PR TITLE
Added NormalizedPosition to MouseState

### PR DESCRIPTION
**Pull request by burnss9**
### Purpose of this PR

Add a normalized mouse position to the MouseState class. Will add a bit of convenience for transforming mouse coordinates to 3D space.

### Testing status

I've tested the NormalizeMousePosition method, other than that admittedly no testing. Fairly straightforward changes though, any time _mouseState.Position is set I just added the NormalizedPosition set.

### Comments

In my pull request for ObjectTK I've added a method to the Camera class that takes the normalized coordinates and returns a Ray starting from camera position with direction towards the point on the near plane that was clicked.

### CODE REVIEW

**Comment by jvbsl** [comment]
I don't really see that much of a benefit from that tbh. For transforming screen coordinates there is the Vector3.Unproject, which pretty much does the same normalization, well and the unproject as well ofc. If you think there is something which I currently just can't think of, please do tell.
Another thing is that I don't see why we would wan't to calculate it everytime even though most times it isn't needed.

**Comment by burnss9** [comment]
I think you're probably right, I was unaware of `Vector3.Unproject`. Only reason I have left that I can think of is that it makes it easier to pass this responsibility off to something other than the window. Currently to use Vector3.Unproject you'd need to pass a reference to the window anywhere you want to use it. Might not be a good enough reason. Though I think worrying about the calculation cost here is a bit silly personally. More just about the design

**Comment by burnss9** [comment]
Yeah thinking about this more I don't think this is really a necessary change, thank you for the feedback 😄

**Comment by jvbsl** [comment]
Yeah no problem, thanks anyway for the suggestion though, highly appreciated ;)

**Pull request closed without merging**
