### PR TITLE
Add a .NET Standard 2.0 project for OpenTK.

### PR DESCRIPTION
**Pull request by mellinoe**
This will still need a bit of iteration and cleanup, but this shows how little needs to be changed to get OpenTK working on .NET Standard 2.0. I haven't fully integrated this into the build (primarily because I don't understand it), but it can be built manually (`dotnet build src/OpenTK/OpenTK.NS20.csproj`), as long as the rewriter project has already been built.

I'm not really sure about the "MINIMAL"-related changes. Those are not necessarily correct -- I just hacked it up real quick to get things working.

NOTE: This doesn't include the DllMap-related changes that need to be made to run parts of the library on .NET Core. Those parts, as far as I can remember, are the SDL2 backend and OpenAL bindings.

@Nihlus

### CODE REVIEW

**Comment by Nihlus** [comment]
Thanks for the PR! However, I think we misunderstood each other when we talked about this. Adding a separate project for .NET Standard 2.0 is not our intention, since there's no real point in doing so if we're going to split the library and only target std2 in the future.

I would very much like to see the changes to the rewriter - and only the changes to the rewriter - as a pull request. It is a separate and independent change from adding a project or changing the way we load native libraries, which we can merge without affecting the rest of the library. 

I'm going to close this PR, but please resubmit the rewriter changes.

**Comment by JimSEOW** [comment]
@mellinoe  You have already created the OpenTK.NETCore.
UWP6.0 is due in a few days (end of August 2017) to make .NET Standard First Class in ALL UWP ecosystem.  e.g. **XBox**, IoT Core, Future **Win10 on ARM** in addition to W10.

It is a great idea to create a stable version of OpenTK.NETstandard2.0 

Hopefully a simple sample of UWP XAML sample using OpenTK.NETStandard2.0 that is usable in e.g. **HoloLens**, XBox without too much effort.

**Comment by mellinoe** [comment]
@JimSEOW I'm not sure there's much value in using OpenTK in a UWP app. You are much better off using Win2D or SharpDX (D3D11/12) when targeting that platform. Just my opinion, though -- I don't do any UWP development.

**Comment by JimSEOW** [comment]
@mellinoe  for 2D cross platform, the best option is SKiaSharp. for 3D cross platform, OpenGL for .NET Standard 2.0 looks promising.

SharpDX is unfortunately, when comes to UWP Interop, is poor with **working** C#  samples shared among the community.  

With Microsoft moving towards Mixed Reality and 3D Remix, UWP XAML interop is the key for democratizing 3D for C# community across IoT Core, W10A and W10.  

>  don't do any UWP development.

mellinoe, I went to CoreFX github site, I was refereed to you. **We need someone with UWP XAML to assist you** to address the missing gaps in  beyond .NET standard 2.0 future milestones.

@Nihlus  Sorry for hijack here.   I use OpenTK User Control for WinForm and WPF (XAML) for > 6 years. 

Now moving to UWP, writing once for UWP XAML or XAMARIN FORMS XAML, allows me to deploy EVERY WHERE. IT is amazing.  Isn't this the vision of OpenTK?

**Comment by mellinoe** [comment]
@JimSEOW I don't really want to bug the OpenTK folks more, since your questions are mostly unrelated to OpenTK (I think?) -- could you file an issue elsewhere if you'd like to continue the discussion?

**Comment by JimSEOW** [comment]
@mellinoe Done, I brought it to CoreFX under UWP6.0 milestone

**Pull request closed without merging**
