### PR TITLE
[3.0] Optimized Quaternion to Matrix3/4/3d/4d

### PR DESCRIPTION
**Pull request by NogginBops**
### Purpose of this PR

Optimize the `CreateFromQuaternion` function for `Matrix3/4/3d/4d`.
This is the same change as #1189 

### Testing status

Could not get 3.3 to compile on my computer due to missing `AssemblyInfo` file and a whole bunch of other errors.

### CODE REVIEW

**Comment by varon** [comment]
@NogginBops  - would love to merge, but we've had some reports for 4.x having some difficulties. Any ideas on that?

**Comment by varon** [comment]
For the compile, everything is done via the `build.sh` or `build.cmd` script. It's janky but should work for the initial setup at least.

**Comment by leezer3** [comment]
https://github.com/opentk/opentk/pull/1087

The Quaternions are iffy as anything.

Your fix appears to be correct, but if there aren't other nasties of this type lurking I'll be surprised......

**Comment by NogginBops** [comment]
Yeah the `Quaterniond` class doesn't even have tests so those are very likely to have some weird stuff in them.

**Comment by varon** [comment]
@leezer3  - I'm happy to merge and do a release of this for you if it's useful. 

Just let me know and we can get this in. Same thing for the Quateriond pr in #1087 .

**Comment by leezer3** [comment]
Not personally.

I use my own math library, OpenTK is just for windowing / input really.

**Comment by NogginBops** [comment]
Merging this as these changes have been used in OpenTK 4 for a while with no reported issues so I think we can consider this stable enough.

**Pull request merged**
