### PR TITLE
Change to .NET 4.5

### PR DESCRIPTION
**Pull request by xanather**
Should be good. Nothing changed compared to https://github.com/opentk/opentk/pull/243 just that the PR is targeting the net45 branch now.

### CODE REVIEW

**Comment by Frassle** [comment]
Thanks the .travis.yml needs looking at to fix the travis build issue. Should be as simple as removing the Mono 2 reference from it. If you could fix that I'll merge the branch.

**Comment by xanather** [comment]
The bot couldn't handle that one line removal :P. Looks like the build didn't even initiate (says Error not Failure)

**Comment by LaylConway** [comment]
I think the bot just dropped it on the floor accidentally, it just needs a retry.

**Comment by xanather** [comment]
Am I able to re-initiate the bot? Or must the administrator of the bot do it?

**Comment by Frassle** [comment]
I'm going to see about rewritting the travis.yml for the main develop line. If you rebase on that it should then be easier to remove the mono 2 stuff, I'll nudge here when my stuff is done.

**Comment by Frassle** [comment]
Ok commit https://github.com/opentk/opentk/commit/bd9ff3a3200c50b8862c8dbc800e51548b7cae12 is in develop. If you rebase on top of that it you can remove the " - 2.10.8" line and everything should work ok.

**Comment by xanather** [comment]
Fingers crossed!

**Comment by Frassle** [comment]
OK Travis worked. Can you clean up the commits so they're parent is the current develop (rebase on top of bd9ff3), you'll have to push --force that change but it will update this PR.

**Comment by Frassle** [comment]
Cleaned up the branch and rebased, put into pull request #248. Will merge that shortly, closing this.

**Pull request closed without merging**
