### PR TITLE
Enable OpenGL ES3 with Angle

### PR DESCRIPTION
**Pull request by l3m**
This pull request is a basic implementation of OpenGL ES3 support via Angle for OpenTK. 

A demo that uses OpenGL ES 3 with Angle based on @thefiddler's opentk-wpf demo can be found [here](https://github.com/l3m/opentk-wpf/tree/angle-es3).

### Open Questions

In order to use desktop OpenGL ES via Angle, some knowledge should be exposed to the user. This is necessary because Angle defaults to D3D9, but requires D3D11 for ES3, and OpenTK should use ```eglGetPlatformDisplayEXT``` to get the display instead of the normal ```eglGetDisplay```. 

This is currently solved by àllowing a user to set ```GraphicsContextFlags.Angle```, but I am not sure if this is the correct approach. 

In addition, it should ideally be possible for a user who wants to use OpenTK with Angle to choose the backend (at the moment D3D9, D3D11, but they are working on native OpenGL, too). 

Any ideas how to best expose this choice? 

I see the following options
- GraphicsContextFlags.Angle and choose automatically
    - D3D9 for ES2 
    - D3D11 for ES3
- GraphicsContextFlags.AngleD3D9, .AngleD3D11 and let the user choose explicitly 

@thefiddler @Frassle What do you think?

### CODE REVIEW

**Comment by Frassle** [comment]
This looks good! I'll try and put some time aside Sunday to see how it works on my machine. As for the ContextFlags it's nice if we can work it out automatically, but it would be a lot simpler to just ask the user for exactly what the want (i.e. AngleD3D9 and AngleD3D11 flags, and when it's done AngleGL I guess)

**Comment by l3m** [comment]
I updated my prq to the following behavior: 

If a user specifies ```GraphicsContextFlags.Angle```, OpenTK will choose the best backend, which is D3D9 for ES2, D3D11 for ES3. 

Alternatively, a user can explicitly ask for a specific backend: 
- ```GraphicsContextFlags.AngleD3D9```
- ```GraphicsContextFlags.AngleD3D11```
- ```GraphicsContextFlags.AngleOpenGL```

**Comment by Frassle** [comment]
So it looks like GraphicsContextFlags.Embeded is also needed so that the Egl Embedded factory is picked up at Source\OpenTK\Graphics\GraphicsContext.cs:134.

That picks up the EGL factory and calls GetAngleDisplay but eglGetPlatformDisplayEXT isn't found in the libEGL entrypoints.

**Comment by l3m** [comment]
> So it looks like GraphicsContextFlags.Embeded is also needed so that the Egl Embedded factory is picked up at Source\OpenTK\Graphics\GraphicsContext.cs:134.

Yes. I am not sure it makes sense to not require that. Does it? 

I am happy to change this to your preferred behavior.

> That picks up the EGL factory and calls GetAngleDisplay but eglGetPlatformDisplayEXT isn't found in the libEGL entrypoints.

It requires a recent angle - I compiled the one I use myself from the chromium repo.  The windows dll is also in my demo branch.

**Comment by Frassle** [comment]
> > So it looks like GraphicsContextFlags.Embeded is also needed so that the Egl Embedded factory is picked up at Source\OpenTK\Graphics\GraphicsContext.cs:134.

> Yes. I am not sure it makes sense to not require that. Does it?

Indeed. Logic should probably be changed so current checks for `if embeded` are turned into `if embeded or angle`.

> It requires a recent angle - I compiled the one I use myself from the chromium repo. The windows dll is also in my wpf-angle repo.

Hmm, maybe I screwed up with DLLs I thought I had copied the one out of your wpf repo. I'll give it another go during the week.

**Comment by l3m** [comment]
Ok, so I noticed that there are angle dlls in the OpenTK repo itself. I updated those. 

In addition, I made it so that GraphicsContext silently enabled the ```GraphicsContextFlags.Embedded``` flag when a user specifies ```.Angle``` or any of the specific angle flags.

**Comment by Frassle** [comment]
Closed on purpose?

**Comment by l3m** [comment]
I completed my work and now have a version of OpenTK with OpenGL|ES3 based on Angle, including extracting the share handles of the Direct3D textures for Wpf interop without copies.

I will make a new pull request based on current develop with my changes later today or tomorrow. 

I thought this was better since I touched most of the stuff here again, my current version is cleaner and this avoids superfluous changes...

**Comment by Frassle** [comment]
Fair enough :) Looking forward to it

**Pull request closed without merging**
