### PR TITLE
[WIP] [4.0] Begin moving Input to OpenTK.Input

### PR DESCRIPTION
**Pull request by devvoid**
### Purpose of this PR

* Description of feature/change: Move all input-related code out of OpenTK and into OpenTK.Input.
* Which part of OpenTK does this affect: Input.
* Links to screenshots, design docs, user docs, etc: None yet.

### Testing status

* No testing as of yet.

### Comments

* None.

### CODE REVIEW

**Comment by devvoid** [comment]
Last commit name is somewhat misleading. The mouse classes used floats internally, but for some reason casted them to ints when returning to the user. That just updates the getters/setters to use floats for consistancy's sake.

**Comment by DylanFPS** [comment]
Awesome! Will see what the rest of the team think about using ADL instead of the rewriter (#854) before I make my OpenGL PR.

**Comment by DylanFPS** [comment]
FTR: this PR is now blocked by the GLFW PR at #867.

**Comment by devvoid** [comment]
This has been discussed on the official Discord a while back, but I want to put it here just for clarity.

The plan for this PR is just a quick and dirty port of Input to work with the new GLFW-based windowing system. However, Input has a lot of problems, old code, and things that don't work.

After the simple port job is finished, I'll work on giving Input the love and attention it needs in a separate PR, maybe for 4.0, maybe for 5.0 (depending on how far along the rest of the project is by the time I get there). This should hopefully modernize the code and fix several longstanding issues.

This is just the current plan, it may change depending on how much modification is necessary to use GLFW instead of SDL/native.

**Comment by DylanFPS** [comment]
A 4.1 can always be made for input if its just a fixer-upper and doesn't change any of the public API surface, don't forget that each subsystem is versioned independently (at the minor level), but I think we just need to get 4.0 out as fast as possible at the moment.

**Comment by devvoid** [comment]
I had to delete the fork this was based on so I could clone the repo for #867 and help out there. Saved a diff of all the changes there, will reopen with a new PR when GLFW is ready to go.

**Pull request closed without merging**
