### PR TITLE
Fixed MINIMAL and NO_SYSDRAWING compilation

### PR DESCRIPTION
**Pull request by dellis1972**
The MINIMAL build did not work, there we multiple build errors. This commit fixed up the MINIMAL + NO_SYSDRAWING version of OpenTK. It adds $(Configuration)Minimal build configurations to separate it out from the normal debug and release builds.

The good news is that this should allow MonoGame to use the NO_SYSDRAWING version for its unified OpenTK platform, also it should help when porting to corefx.

### CODE REVIEW

**Comment by dellis1972** [comment]
Any feedback on this?

**Comment by Frassle** [comment]
I'd normally leave this to @thefiddler as he could check it works on a Xamarin build, but given the Minimal build is broken anyway (as you say) and he doesn't seem to be around much atm I'll see about getting this merged.

**Comment by Frassle** [comment]
#264 removed all references to SYS_NODRAWING, given I haven't heard anything else about this change if you want to fix up the conflicts I'm happy to merge it.

**Comment by dellis1972** [comment]
@Frassle will do

**Pull request merged**
