### PR TITLE
License headers #361

### PR DESCRIPTION
**Pull request by varon**
See #361

### CODE REVIEW

**Comment by amulware** [comment]
Thanks for making the effort!
Judging by the travis log, you messed up a bunch of things though.

Can you look over that and fix it?

**Comment by amulware** [comment]
Here is an example of one of the things that went wrong (I assume you used a script for this?):
https://github.com/varon/opentk/blob/0239f85f8b744c5135473ee70bad2717bc2b3e72/Source/OpenTK/Math/Box2d.cs#L4

The full list of errors can be found in the log here:
https://travis-ci.org/opentk/opentk/jobs/114659115#L1126

**Comment by varon** [comment]
Should be ready to merge.

**Comment by cra0zy** [comment]
It's not correct, for example you can't modify all the files to contain the license text, there are files that are for example in Public Domain, and their license should stay unchanged.

**Comment by varon** [comment]
@cra0zy The issue #361 reads all files. If this is not correct, it should have been addressed there.

**Comment by cra0zy** [comment]
> @cra0zy The issue #361 reads all files. If this is not correct, it should have been addressed there.

Yes, it says all files, but it's meant as all files it can be changed in.

You cannot change license of a file midway unless you wrote the file yourself, or asked the people who authored the code to change it.

If you don't know what you are doing with this, please close the PR and let someone else do it.

**Comment by varon** [comment]
@cra0zy, I would really appreciate a more friendly tone from you. I'm all for directness, but immediately dismissing a contributor's work isn't very productive.

I shouldn't need to remind you, but it seems like I'll have to: it's your obligation as a package maintainer to make issues as clear and explicit as possible, as well as provide assistance to those trying to contribute. It's a pretty gross oversight to say "all files" but not mean "all files". Above and beyond that, it's hilarious that you subsequently shift the blame onto a contributor for such an unclear brief, especially when I even explicitly asked about this before beginning the PR:

> Should I do a PR of the proposed snippet on all files?

to which I received the response from you

>Sure, go ahead.

The code changes here were done with scripts and a few fixes by hand where it tripped up. Obviously I didn't read the source code of every file, so I had no means to determine that we had divergent licenses to take care of. Here's a quick mention of @amulware so he can see the current issues with this PR, and get some degree of visibility of the situation.

Finally, as for the business end of this PR: It would make no sense to close it as most of the work is already done. Can you provide a listing of the files you want reverted?

**Comment by cra0zy** [comment]
@varon Sorry if I came a bit strong, but long story short, licenses aren't something that I want being messed up, you really have to know what you are doing and go through each file by hand and check will you:
1) Add new license text
2) Keep existing license
3) Don't add license

And we should also move the contributor names that can appear in licenses to a file (there is one in the repo, forgot it's name).

**Comment by wcdeich4** [comment]
@cra0zy you said "And we should also move the contributor names that can appear in licenses to a file (there is one in the repo, forgot it's name)." 

--- isn't there some value in allowing the original file author's name to be at the top? That way, people can try to reach out to the author for help - for example that's how I figured out @thefiddler's real name is Stefanos Apostolopoulos

**Comment by cra0zy** [comment]
> @cra0zy you said "And we should also move the contributor names that can appear in licenses to a file (there is one in the repo, forgot it's name)."
> 
> --- isn't there some value in allowing the original file author's name to be at the top? That way, people can try to reach out to the author for help - for example that's how I figured out @thefiddler's real name is Stefanos Apostolopoulos

Point well made, I agree.

**Comment by varon** [comment]
>go through each file by hand

@cra0zy I'm going to close this PR, then. There's no way I have time for that, and I doubt anyone else does.

**Pull request closed without merging**
