### PR TITLE
Cleanup of different parts for 4.0.1 :)

### PR DESCRIPTION
**Pull request by NogginBops**
### Purpose of this PR

Does some cleanup and fixes for stuff that was missing in 4.0

### Testing status

It builds.

### CODE REVIEW

**Comment by NoneGiven** [comment]
This is not necessarily related to this PR, but it seems too minor to open an issue: it's weird to have `Keys.Minus` but `Keys.KeyPadSubtract`, and I think `Minus` should be used for both.

Also, congrats on the 4.0 release!

**Comment by HughPH** [comment]
> This is not necessarily related to this PR, but it seems too minor to open an issue: it's weird to have `Keys.Minus` but `Keys.KeyPadSubtract`, and I think `Minus` should be used for both.

They are two different keys, with two different scancodes. Most games would differentiate between KeyPadSubtract and Minus when you configure keybindings - and you would want them to.

**Comment by NogginBops** [comment]
@HughPH How I interpreted the message was that the weird part wasn't that they are separate keys, it's that they use different words "Minus" and "Subtract" when they both mean the same thing. Though I think the reason they use different words is because the numpad buttons are thought of as actions rather than characters. So subtract, add, multiply would be the keypad names while minus, plus, asterisk would be the non-numpad variants

**Review by varon — APPROVED** [review]
LGTM.

**Comment by varon** [comment]
Merged! Thanks @NogginBops !

**Pull request merged**
