### PR TITLE
Fix IL generation for some edge case GLES functions.

### PR DESCRIPTION
**Pull request by NogginBops**
### Purpose of this PR

This PR fixes a IL generation issue where bad IL was generated for `glExtGetProgramBinarySourceQCOM`.
This issue was found in https://github.com/dotnet/runtime/issues/59138 where the AoT compiler didn't want to compile the function because there where more stuff on the stack than there was supposed to.
In reality this function was fundamentally broken and would not have worked when called, this PR fixes this.

This PR also modifies one function so that it doesn't throw exceptions that where then caught, hopefully improving performance of the rewriting step.

### Testing status

Builds.
The IL has been checked in ILSpy and it generates reasonable decompilation results compared to before these changes.

This code has now been put through the AOT compiler and it compiles as it should.

### Comments

The issue was that the modified function should have stored the result in a local variable and not leave anything on the stack. This is what all of the branches in this function where doing except in the case where the length parameter is a simple dereference.

#1286 is somewhat related to this fix.

Here follows a list of the overloads that are fixed by this change:
```
ES30.GL/Qcom::ExtGetProgramBinarySource(System.Int32,OpenTK.Graphics.ES30.All,System.String&,System.Int32[])
ES30.GL/Qcom::ExtGetProgramBinarySource(System.Int32,OpenTK.Graphics.ES30.All,System.String&,System.Int32&)
ES30.GL/Qcom::ExtGetProgramBinarySource(System.Int32,OpenTK.Graphics.ES30.All,System.String&,System.Int32*)
ES30.GL/Qcom::ExtGetProgramBinarySource(System.Int32,OpenTK.Graphics.ES30.ShaderType,System.String&,System.Int32[])
ES30.GL/Qcom::ExtGetProgramBinarySource(System.Int32,OpenTK.Graphics.ES30.ShaderType,System.String&,System.Int32&)
ES30.GL/Qcom::ExtGetProgramBinarySource(System.Int32,OpenTK.Graphics.ES30.ShaderType,System.String&,System.Int32*)
ES30.GL/Qcom::ExtGetProgramBinarySource(System.UInt32,OpenTK.Graphics.ES30.All,System.String&,System.Int32[])
ES30.GL/Qcom::ExtGetProgramBinarySource(System.UInt32,OpenTK.Graphics.ES30.All,System.String&,System.Int32&)
ES30.GL/Qcom::ExtGetProgramBinarySource(System.UInt32,OpenTK.Graphics.ES30.All,System.String&,System.Int32*)
ES30.GL/Qcom::ExtGetProgramBinarySource(System.UInt32,OpenTK.Graphics.ES30.ShaderType,System.String&,System.Int32[])
ES30.GL/Qcom::ExtGetProgramBinarySource(System.UInt32,OpenTK.Graphics.ES30.ShaderType,System.String&,System.Int32&)
ES30.GL/Qcom::ExtGetProgramBinarySource(System.UInt32,OpenTK.Graphics.ES30.ShaderType,System.String&,System.Int32*)
ES20.GL/Qcom::ExtGetProgramBinarySource(System.Int32,OpenTK.Graphics.ES20.All,System.String&,System.Int32[])
ES20.GL/Qcom::ExtGetProgramBinarySource(System.Int32,OpenTK.Graphics.ES20.All,System.String&,System.Int32&)
ES20.GL/Qcom::ExtGetProgramBinarySource(System.Int32,OpenTK.Graphics.ES20.All,System.String&,System.Int32*)
ES20.GL/Qcom::ExtGetProgramBinarySource(System.Int32,OpenTK.Graphics.ES20.ShaderType,System.String&,System.Int32[])
ES20.GL/Qcom::ExtGetProgramBinarySource(System.Int32,OpenTK.Graphics.ES20.ShaderType,System.String&,System.Int32&)
ES20.GL/Qcom::ExtGetProgramBinarySource(System.Int32,OpenTK.Graphics.ES20.ShaderType,System.String&,System.Int32*)
ES20.GL/Qcom::ExtGetProgramBinarySource(System.UInt32,OpenTK.Graphics.ES20.All,System.String&,System.Int32[])
ES20.GL/Qcom::ExtGetProgramBinarySource(System.UInt32,OpenTK.Graphics.ES20.All,System.String&,System.Int32&)
ES20.GL/Qcom::ExtGetProgramBinarySource(System.UInt32,OpenTK.Graphics.ES20.All,System.String&,System.Int32*)
ES20.GL/Qcom::ExtGetProgramBinarySource(System.UInt32,OpenTK.Graphics.ES20.ShaderType,System.String&,System.Int32[])
ES20.GL/Qcom::ExtGetProgramBinarySource(System.UInt32,OpenTK.Graphics.ES20.ShaderType,System.String&,System.Int32&)
ES20.GL/Qcom::ExtGetProgramBinarySource(System.UInt32,OpenTK.Graphics.ES20.ShaderType,System.String&,System.Int32*)
ES11.GL/Qcom::ExtGetProgramBinarySource(System.Int32,OpenTK.Graphics.ES11.All,System.String&,System.Int32[])
ES11.GL/Qcom::ExtGetProgramBinarySource(System.Int32,OpenTK.Graphics.ES11.All,System.String&,System.Int32&)
ES11.GL/Qcom::ExtGetProgramBinarySource(System.Int32,OpenTK.Graphics.ES11.All,System.String&,System.Int32*)
ES11.GL/Qcom::ExtGetProgramBinarySource(System.Int32,OpenTK.Graphics.ES11.ShaderType,System.String&,System.Int32[])
ES11.GL/Qcom::ExtGetProgramBinarySource(System.Int32,OpenTK.Graphics.ES11.ShaderType,System.String&,System.Int32&)
ES11.GL/Qcom::ExtGetProgramBinarySource(System.Int32,OpenTK.Graphics.ES11.ShaderType,System.String&,System.Int32*)
ES11.GL/Qcom::ExtGetProgramBinarySource(System.UInt32,OpenTK.Graphics.ES11.All,System.String&,System.Int32[])
ES11.GL/Qcom::ExtGetProgramBinarySource(System.UInt32,OpenTK.Graphics.ES11.All,System.String&,System.Int32&)
ES11.GL/Qcom::ExtGetProgramBinarySource(System.UInt32,OpenTK.Graphics.ES11.All,System.String&,System.Int32*)
ES11.GL/Qcom::ExtGetProgramBinarySource(System.UInt32,OpenTK.Graphics.ES11.ShaderType,System.String&,System.Int32[])
ES11.GL/Qcom::ExtGetProgramBinarySource(System.UInt32,OpenTK.Graphics.ES11.ShaderType,System.String&,System.Int32&)
ES11.GL/Qcom::ExtGetProgramBinarySource(System.UInt32,OpenTK.Graphics.ES11.ShaderType,System.String&,System.Int32*)
```

### CODE REVIEW

**Comment by NogginBops** [comment]
This has now been tested with the AOT compiler and it compiled it as it should. Will consider this patch tested and will merge it now.

**Comment by kant2002** [comment]
@NogginBops may I ask what's approximate timeframe where this patch would be released? I was trying to compile SS14 using NativeAOT and this is what I'm hitting.

**Comment by NogginBops** [comment]
I put this on the 4.7.0 milestone but there are a few Para there that need a bit more work. I'm starting to think that an in-between version is needed where we can release what is ready atm and then get the rest of the stuff ready for 4.7.0. I'm not exactly sure if this is the way to go, but I think I'll have time to look at this closer tomorrow, so I'll try to get you a real answer then. @kant2002

**Comment by kant2002** [comment]
I’m definitely not in rush. From what I see SS14 is long way to be AOT friendsly(or that’s RobustToolbox?). Maybe I have to use custom build version and test first

**Pull request merged**
