### PR TITLE
[TEMP] Add sample projects using opentk 4.0

### PR DESCRIPTION
**Pull request by frederikja163**
### Purpose of this PR

* Adds a hello triangle and a hello sprite program to the tests folder
* Functions as tests to the library aswell as a reference point for people familiar with opengl getting into opentk 4.0

### Testing status

* Both programs are running on my pc with no errors, as they are simple i have no reason to expect results vary on other machines.

### Comments

* More thorough tutorials will be added once opentk 4.0 or opentk 5.0 comes out, at that point i will likely go over all the tutorials again and check them through for writing mistakes etc. and redo most of them.

### CODE REVIEW

**Comment by NogginBops** [comment]
Shouldn't this go into the [learnopentk](https://github.com/opentk/LearnOpenTK) repository?

Also feels weird to put this in the tests folder as this isn't really a test (doesn't run in automated testing).

**Comment by daerogami** [comment]
Isn't this the purpose of [opentk-examples](https://github.com/opentk/opentk-examples)?

**Comment by frederikja163** [comment]
I will move this at a later date, will keep it here for now tho.

**Comment by varon** [comment]
Spoke with fred about this.

We'll integrate these into the examples and learnopentk repo

**Pull request closed without merging**
