### PR TITLE
Add OpenGL 4.6 Support

### LINKED ISSUE #621: Add OpenGL 4.6 Support
### Description

OpenGL 4.6 has recently been released, [here](https://www.khronos.org/news/press/khronos-releases-opengl-4.6-with-spir-v-support) is some information regarding it's additional features.

It would be great to see OpenGL 4.6 support within OpenTK.

### Additional Information

* [OpenGL 4.6 Core Profile Specification](https://khronos.org/registry/OpenGL/specs/gl/glspec46.core.pdf)
* [OpenGL Shading Language 4.60 Specification](https://khronos.org/registry/OpenGL/specs/gl/GLSLangSpec.4.60.pdf)

The above information and more can be found [here](https://www.khronos.org/opengl/).

### PR DESCRIPTION
**Pull request by Frassle**
Fixes #621

### CODE REVIEW

**Comment by tzachshabtay** [comment]
Maybe also update the readme (it says OpenGL 4.4).

**Comment by Nihlus** [comment]
Very nice - I didn't think it would be this easy :+1: Provided nothing else has changed, this should just work.

**Comment by Frassle** [comment]
I'm away all weekend so if someone else wants to test and merge this feel free.

**Comment by Frassle** [comment]
Builds and runs my OpenGL 4 programs with no problems.

**Pull request merged**
