### PR TITLE
Remove example and legacy code.

### PR DESCRIPTION
**Pull request by varon**
This PR removes old and example code.

Should we remove `Test.API.Desktop`? I don't think it's even compiled as part of the standard build.

### CODE REVIEW

**Comment by varon** [comment]
Seems as though `Test.API.Desktop` is actually being built. better to leave it in for now.

**Comment by cra0zy** [comment]
Seems good to me, merging!!!

**Comment by tzachshabtay** [comment]
@varon this PR also removed the Android/IOS samples which were actually pretty recent (https://github.com/opentk/opentk/pull/391), can those be brought back?

**Comment by varon** [comment]
The intent was to set up the examples in a separate repository, as this is a way better reflection of the expected project structure of someone using OpenTK. Most importantly, it shows how to utilize OpenTK as a NuGet package, rather than source inclusions.

Nobody has gotten round to that yet, though, so if you'd like to help out, that would be hugely appreciated.

**Comment by tzachshabtay** [comment]
Well, IOS & Android are not yet a part of the NuGet package. Once they're in and there's a repo for examples, I can try to bring back those lost examples.

**Comment by varon** [comment]
We're not even sure on the status of the iOS and Android packages - I thin they build, but I'm not sure about whether or not they WORK.

if we can get some reports of them functioning as intended, I'll be happy to release packages for them.

**Comment by tzachshabtay** [comment]
I can report that Android works for me (my repository: https://github.com/tzachshabtay/MonoAGS), using OpenGL ES 2.0 & OpenAL. Tested on a Nexus5X and the android emulator.
IOS- still working on it (though the provided example from the original PR did work on the ios simulator).

**Pull request merged**
