### PR TITLE
Update bindings from OpenGL-Registry

### PR DESCRIPTION
**Pull request by Frassle**
Updates the OpenGL bindings from commit 681c365c012ac9d3bcadd67de10af4730eb460e0.

https://raw.githubusercontent.com/KhronosGroup/OpenGL-Registry/681c365c012ac9d3bcadd67de10af4730eb460e0/xml/gl.xml

### CODE REVIEW

**Comment by Frassle** [comment]
Hmm seems the specs updated more than the binder can currently handle.

**Comment by Frassle** [comment]
Ah was just DebugProc is needed in ES11 now as well. Simple fix.

**Comment by Nihlus** [comment]
Looks simple enough, but the diffs are too large to view heh. What are the main highlights?

**Comment by Frassle** [comment]
Mostly loads of new typed enums. Things like texture format, type, target are now typed enums rather than just being GLenum and a load of constants.

**Pull request merged**
