### PR TITLE
[WIP] STB Bindings(stb_image primarily)

### PR DESCRIPTION
**Pull request by Khhs167**
### Purpose of this PR

My idea is simple: Add STB bindings to OpenTK. Why? Well, because a lot of projects I've worked with(Silk.NET, LWJGL, LearnOpenGL) have used/supported some form of asset importing library, and it'd be perfect if OpenTK did too! My main focus is going to be stb_image, since it feels like the most commonly used library in the "STB group", and it could be slotted into LearnOpenTK.

### Testing status

Testing ideas would most likely be to just try and load images with various settings, and compare them to binary data already calculated(or loaded using some other library beforehand, e.g ImageSharp), at least for stb_image. Once again, I'll pour my main focus onto stb_image, and so I don't think I should try to come up with tests before we know what to do other than that.

### Comments

Don't have too many comments, but I hope this was understandable. I'll be trying to chip off work at times on this, and we'll see how it goes!

Also, sorry for specifying I'll be focusing on stb_image, but that's just how it is, and I wanted to make that clear.

### CODE REVIEW

**Comment by Khhs167** [comment]
Asking for a bit of help now, how would I go about to bundle the stb_image binaries alongside the library? They need to be build and bundled, that much I know, just not sure how to do so though

**Comment by utkumaden** [comment]
Thank you for reaching out to commit. Bundling in an image loader has been discussed in the past, but it was deemed out of scope. I would wait for a statement from the maintainers before you continue working on this.

stb_image is available on nuget for C# users with the package [StbImageSharp](https://www.nuget.org/packages/StbImageSharp), and my personal recommendation whenever somebody asks about image loading in our discord server. Whilst it would be convenient to have it directly in OpenTK, it increases the already suffering binary size as well as maintenance and the lack of modularity.

Directly depending on binaries that have to be distributed is also asking for trouble, in my opinion, because supporting Linux and every different libc version is already enough pain in its own.

**Comment by NogginBops** [comment]
Thanks for the PR! This subject has been discussed in #1354, and I think the conclusion we came to there as to either use https://github.com/StbSharp/StbImageSharp or https://github.com/tom94/stbi-sharp. Adding bindings would be a duplicated effort as these projects already do a good job at exposing stb_image.h to c#. We really appreciate the engagement and if you wish to contribute with something else there we would greatly appreciate the help!

As for your question related to stb_image binaries, yes you would need to compile them (for all different supported platforms) and put them inside a nuget package. This is something we are doing for glfw, but I'm basically the only person with any insight into how that happens. I would like to avoid adding more native dependencies like that.

**Comment by Khhs167** [comment]
Are we closing the PR then? The natives issue could be done the StbImageSharp way and just straight up port the source code to C#.

Just wondering if I should keep on going or if we're closing

**Comment by NogginBops** [comment]
I think we unfortunately should close this. 
If we where to do what StbImageSharp does we could just as well put work into StbImageSharp instead of making a duplicate effort imo.

Though if you have any reasons for why we should be doing it in this repo (instead of improving StbImageSharp ) I would listen with open ears.

**Comment by NogginBops** [comment]
The scope of OpenTK atm is OpenGL, OpenAL, OpenCL, and windowing. Potentially adding OpenXR.

But I don't think texture loading is something that fits into that category.
I can understand that "all in one place" is somewhat nice, but texture loading is not a one size fits all.

**Comment by Khhs167** [comment]
All right, feels like we've decided!

Closing(I'll be glad to help if anything comes up(and I have the energy)!)

**Pull request closed without merging**
