### PR TITLE
Add less, greater, lessEqual and greaterEqual operators.

### PR DESCRIPTION
**Pull request by txdv**
I did not do the same for all the Math objects since I Wanted to hear some feedback first on whether the idea in general is ok or not.

### CODE REVIEW

**Comment by varon** [comment]
Thanks for the PR.

I'm not sure of the applicability of adding these operators, as comparisons between vectors doesn't make much mathematical sense. I'm generally against merging this, as  I think it introduces some confusing behaviour:
`Vec3(1,0,0) > Vec3(0,0,0) == false` would definitely get a "WTF" from me.

 If you did want to compare, the only metric that would make 'sense' to me is by magnitude. However, I'd argue it's vastly more clear as to what's going on if you were to compare by the square of the length:
`v1.LengthSquared > v2.LengthSquared`.

**Comment by txdv** [comment]
Doesn't a Vector3 also represent a dot in space?

Would it make sense for one dot to be greater than other?

**Comment by varon** [comment]
Only one one axis at a time.

**Comment by mellinoe** [comment]
Yeah, it doesn't really make much sense to describe a vector (or point, or direction, or whatever) as "greater" than another. The most reasonable definition you might be able to give is element-wise, i.e. `operator >` returning a `Vector3` itself. But that isn't very useful, and isn't exactly what you're proposing.

The versions in the PR here are also non-symmetrical, which is weird, and I don't see how it's useful.

```
(1, 0, 0) > (0, 1, 0) == false
(1, 0, 0) < (0, 1, 0) == false
(0, 1, 0) > (1, 0, 0) == false
(0, 1, 0) < (1, 0, 0) == false
```

**Comment by txdv** [comment]
I guess these operations would represent checking if something is a quadrant (of 8 possible).

But you are right, doesn't make sense to have them as a function, I'll just define it on my own in my code as I see fit.

Thanks for your input.

**Comment by varon** [comment]
@txdv I strongly advise against defining these operations in your own code, because they violate the VERY useful property of `∀ x,y: (x > y) ⇒ (x != y) && !(y < x)`

**Comment by txdv** [comment]
Well I'm not going to name them as < and > operators, I'll do it as a function which checks which quadrant the dot is in relation to another dot and probably some kind of matrix which defines the directions.

**Pull request closed without merging**
