### PR TITLE
improvements to Math/Box2

### PR DESCRIPTION
**Pull request by skkestrel**
- add FromDimensions, FromCorners initialization methods
- add Translate, Contains functions
- add equality operators
- stylize ToString the same way as Vector2.ToString
- add double precision Box2d struct

### CODE REVIEW

**Comment by amulware** [comment]
Haven't checked all changes specifically (will do so later), but overall, it looks good.

**Comment by amulware** [comment]
Looking at the code in detail now.

What I noticed:

1. The new static construction methods assume that top<bottom (and left<right, though this may be less controversial), and in fact FromCorners() enforces this constraint (while FromDimensions would happily accept negative width and height).
  The new Contains() method is implemented in a smart way such that it does not rely on this however - it will work no matter if l<r or r<l (same for top and bottom).
2. Contains() is implemented with open bounds on one side, and with closed bounds on the other. That seems strange to me.

@skkestrel can you comment on these two points?

**Comment by skkestrel** [comment]
You bring up a good point of discussion with having the condition that left <= right. The old methods don't enforce this either and as such I did not add such a constraint to FromDimensions either. However since FromCorners does not specify which corners are being passed in it is impossible to have such a method without some kind of constraint on the bounds.

Personally I'm in favour of clamping right and bottom to be greater than left and top in all ctors since I can't think of any use case for a negative dimensioned rectangle, but I neglected to do so as it might break existing code. As such, FromCorners should not technically exist. The reason it's there is because I had it in an old personal fork that did have this constrant but I still thought it might be useful for some.

As for the asymmetric bounds, this is necessary for the interval to look OK. If left <= right then the comparison will yield a closed interval [left, right]. Looking back, I made an oversight in the case if right < left: in tbat case, the interval will be open instead. (right, left). This should be changed to do some branching later if it's decided to not add constraints on the rectangle borders.

Whether or not to enforce that the width of the rectangle is nonnegative is sort of the key here. LMK your thoughts.

**Comment by amulware** [comment]
One big problem I see with adding such constraints is that the type is entirely mutable. So unless we hide the fields behind properties, and add a bunch of checks (and what.. throw exceptions?) the user can always break the constraints.

That would defeat the low-level-ness and performance of the type though, which I do not think is a good idea. So I say we should not have any such constraints.

Regarding `FromCorners()`, we could name the parameters `topLeft` and `bottomRight` or similar. That would help at least to some degree. In the end, the other methods also rely on the names of the parameters to make clear what each of them means, so I would be fine with that.

Regarding `Contains()`, since we are dealing with floats, we could make the argument that <= and < are really the same operator. I can already see confused users asking why 2 is in [0, 2] and not in '(2, 0)', so to speak.

I do not really see a good solution though, unless we want to make the Contains() method a lot more complicated... I like how simple it is.

Here is a proposal:

Add three methods:
```
ContainsFast(Vector2 p) - current implementation, explain behaviour in xml comment
Contains(Vector2 p, bool includeOnBoxBorder) - makes sure the intervals are closed or open, based on parameter, and whether l<r or l>r.
```

Seems a bit complicated/over-engineered...

---

I checked out the implementation of `Rectangle`, and as it happens, that type uses a point and size, and its Contains() method assumes that size is positive.
It does not enforce that constraint at any point though.

This all feels rather icky to me.

**Comment by amulware** [comment]
Actually, regarding my idea with two methods: They could both be called `Contains()`, with one overload simply being more specific (since you give it a parameter) than the other (where the behaviour is... sort of undefined :/ ).

**Comment by skkestrel** [comment]
I agree with your comments on FromCorners. Since there already exists a constructor that takes vectors topLeft and bottomRight, I would then propose to ditch FromCorners.

The two Contains could possibly be merged into one - how about
```
bool Contains(Vector2 point, bool closedRegion = true)
{
    if (closedRegion == Left >= Right)
    {
          return (point.X >= Left != point.X > Right) && (point.Y >= Top != point.Y > Bottom);
    }
    else
    {
          return (point.X > Left != point.X >= Right) && (point.Y > Top != point.Y >= Bottom);
    }
}
```

**Comment by amulware** [comment]
Again I can not decide whether these boolean shortcuts are genius or evil hacks.

That being said, would we not also have to split on whether top<bottom? Otherwise we cover only two out of four cases. Can we be happy with nesting another if-else block inside, and having four different return statements?

**Comment by skkestrel** [comment]
Ah, oops - how about:

```
bool Contains(Vector2 point, bool closedRegion = true)
{
    bool xOK = (closedRegion == Left >= Right) ?
        (point.X >= Left != point.X > Right) :
        (point.X > Left != point.X >= Right);
    bool 

&& (point.Y >= Top != point.Y > Bottom);
    }
    else
    {
          return (point.X > Left != point.X >= Right) && (point.Y > Top != point.Y >= Bottom);
    }
}
```

**Comment by skkestrel** [comment]
Arrgh I was on my phone and mistapped.
 

```
bool Contains(Vector2 point, bool closedRegion = true)
{
    bool xOK = (closedRegion == Left >= Right) ?
        (point.X >= Left != point.X > Right) :
        (point.X > Left != point.X >= Right);
    bool yOK = (same as above);
    return xOK && yOK;
}
```

I think it might be going a bit overboard with the expressions, but we can just split the ternary into a branch if need be.

**Comment by wcdeich4** [comment]
bool Contains(Vector2 point, bool closedRegion = true) sounds like a good idea to me; people can set the variables as they wish & use this function if they chose to do so.  The variable names TopLeft and BottomRight really suggest their intended geometric positions; if people program that wrong, it's on them

**Comment by cyotek** [comment]
Sorry to poke my nose in as it were, but can I suggest you *don't* add optional parameters to a public API, just create separate overloads. If the lib doesn't currently make use of optional parameters, perhaps it is wiser to avoid them full stop. They are probably fine for internals, but I'd avoid them like the plague publicly, especially in a popular lib like OpenTK.

Phil Haack  summed it up the various (subtle) issues that can occur some years ago when they were first introduced.

http://haacked.com/archive/2010/08/10/versioning-issues-with-optional-arguments.aspx/
http://haacked.com/archive/2010/08/12/more-optional-versioning-fun.aspx/

(Apologies again for the random comment!)

**Comment by skkestrel** [comment]
Thanks for the heads up wrt optional parameters. I've made the suggested change.
I've also committed the updated files with the Contains implementation, and they work on the tests on my end with both open and closed boundaries.

**Comment by amulware** [comment]
Thanks for the links @cyotek. You are making a good point. In this case it may not matter much (unlikely to change), but it still seems better practice this way.

@skkestrel I'll look over the changes once more, and if everything seems ok, I'll merge! Thanks for your help and patience. :)

**Comment by amulware** [comment]
Alrighty, looked over it again. Checks out as far as I can tell. :)

@wcdeich4, @cra0zy Does either of you still want to look over this? It has my blessing.

**Comment by cra0zy** [comment]
We need to use a better License header text, something like:
```
// Copyright (c) Open Toolkit library.
// This file is subject to the terms and conditions defined in
// file 'License.txt', which is part of this source code package.
```

@amulware I don't have time to properly go over the code, but I trust in your judgment, so merge it when the above is fixed.

**Comment by skkestrel** [comment]
Thanks for the heads up. I went ahead and copied the license header from some other files (they all seem to have about the same thing)

**Comment by cra0zy** [comment]
The license you copied is no good, the problem is that they display the end year, which should have been updated....

It's much better when there is no years in header files, but instead only a point to License.txt, use the header I prepared.

**Comment by skkestrel** [comment]
Gotcha. This seems to be quite a big problem then, considering that many of the files I browsed through had the same format...

**Comment by amulware** [comment]
We did it!

**Pull request merged**
