### PR TITLE
Add required count attribute overrides

### LINKED ISSUE #659: OpenTK can no longer be used as part of a obfuscated project using ConfuserEX
ConfuserEX needs to read/write all dependencies. Using the latest build of opentk, while trying to write opentk.dll it fails with following exception. Any ideas what that could be?

```
Exception: dnlib.DotNet.Writer.ModuleWriterException: Error calculating max stack value. If the method's obfuscated, set CilBody.KeepOldMaxStack or MetaDataOptions.Flags (KeepOldMaxStack, global option) to ignore this error. 
Otherwise fix your generated CIL code so it conforms to the ECMA standard. 
at dnlib.DotNet.DummyLogger.Log(Object sender, LoggerEvent loggerEvent, String format, Object[] args) in E:\Source\Public\Confuser2\dnlib\src\DotNet\ILogger.cs:line 456
   at dnlib.DotNet.Writer.MetaData.dnlib.DotNet.Writer.IWriterError.Error(String message) in E:\Source\Public\Confuser2\dnlib\src\DotNet\Writer\MetaData.cs:line 2575
   at dnlib.DotNet.Writer.MethodBodyWriterBase.GetMaxStack() in E:\Source\Public\Confuser2\dnlib\src\DotNet\Writer\MethodBodyWriterBase.cs:line 64
   at dnlib.DotNet.Writer.MethodBodyWriter.Write() in E:\Source\Public\Confuser2\dnlib\src\DotNet\Writer\MethodBodyWriter.cs:line 95
   at dnlib.DotNet.Writer.MetaData.WriteMethodBodies() in E:\Source\Public\Confuser2\dnlib\src\DotNet\Writer\MetaData.cs:line 1552
   at dnlib.DotNet.Writer.MetaData.Create() in E:\Source\Public\Confuser2\dnlib\src\DotNet\Writer\MetaData.cs:line 1206
   at dnlib.DotNet.Writer.ModuleWriter.WriteImpl() in E:\Source\Public\Confuser2\dnlib\src\DotNet\Writer\ModuleWriter.cs:line 171
   at dnlib.DotNet.Writer.ModuleWriterBase.Write(Stream dest) in E:\Source\Public\Confuser2\dnlib\src\DotNet\Writer\ModuleWriterBase.cs:line 503
   at Confuser.Core.ConfuserEngine.WriteModule(ConfuserContext context) in e:\Source\Public\Confuser2\Confuser.Core\ConfuserEngine.cs:line 393
   at Confuser.Core.ProtectionPipeline.ExecuteStage(PipelineStage stage, Action`1 func, Func`1 targets, ConfuserContextcontext) in e:\Source\Public\Confuser2\Confuser.Core\ProtectionPipeline.cs:line 135
   at Confuser.Core.ConfuserEngine.RunPipeline(ProtectionPipeline pipeline, ConfuserContext context) in e:\Source\Public\Confuser2\Confuser.Core\ConfuserEngine.cs:line 244
   at Confuser.Core.ConfuserEngine.RunInternal(ConfuserParameters parameters, CancellationToken token) in e:\Source\Public\Confuser2\Confuser.Core\ConfuserEngine.cs:line 175
Failed at 9:59 PM, 0:28 elapsed.
```

### PR DESCRIPTION
**Pull request by Frassle**
### Purpose of this PR

* Fixes #659.
* A number of extension methods from OpenGL don't have the correct information in their XML spec file. Mostly around missing count attributes, but also some const correctness issues. This PR adds overrides so these methods are generated correctly.

### Testing status

* These methods weren't working before. This PR adds count attributes so the CIL is now generated correctly. Verified with manual inspection.

### Comments

* GitHub doesn't handle dependent PR's very well, but this PR depends on #661. The first set of commits (up to "Fix bug where count overrides didn't effect ComputeSize") are from that PR. Suggest that PR is merged first and then this PR is rebased.

### CODE REVIEW

**Comment by tyronx** [comment]
Thanks a lot for the work! Apologies for the lack of knowledge but do you know if there is an easy way I could get a hold of both your PRs and merge it into my fork?

At the same time I could also test your crash fix for #656

**Comment by Frassle** [comment]
```
git fetch git@github.com:Frassle/opentk.git refs/heads/outstr
git merge FETCH_HEAD
```

The outstr PR includes the commits in the bindfix PR so you only need to fetch and merge that one.
Similarly for #656 
```
git fetch git@github.com:Frassle/opentk.git refs/heads/issue656
git merge FETCH_HEAD
```

**Comment by Nihlus** [comment]
This also looks fine. It would be great if you could rebase onto `develop` now that #661 has been merged so we keep the commit history clean.

**Comment by Frassle** [comment]
Away at the moment will rebase it when I'm back next week

**Comment by Frassle** [comment]
Rebased

**Comment by Nihlus** [comment]
Merged. Closes #659.

**Pull request merged**
