### PR TITLE
[Cleanup] Brace Style

### PR DESCRIPTION
**Pull request by Nihlus**
This PR enables the following brace-related rules and corrects violations of them in the codebase.

- SA1012
- SA1013
- SA1500
- SA1503
- SA1505
- SA1508
- SA1509
- SA1519
- SA1520

As an exception, SA1513 was enabled during this PR and should be followed in the future, but a non-configurable exception was encountered that runs contrary to the style rules (blank spaces between switch cases were raising errors). Therefore, it remains disabled with an annotated reason.

Furthermore, it also alters the binding generator to account for these rules, and regenerates the binding files.

### CODE REVIEW

**Comment by amulware** [comment]
I scrolled through the whole thing, and it looks fine.

Here is a list of files where the changes caused more complicated diffs (changed indentation of larger blocks, etc.), in case someone wants to look them over specifically:
```
    src/OpenTK/Platform/Linux/LinuxJoystick.cs
    src/OpenTK/Platform/MacOS/CocoaNativeWindow.cs
    src/OpenTK/Platform/MacOS/HIDInput.cs
    src/OpenTK/Platform/MappedGamePadDriver.cs
    src/OpenTK/Platform/SDL2/Sdl2JoystickDriver.cs
    src/OpenTK/Platform/Windows/WinRawInput.cs
    src/OpenTK/Platform/X11/X11GLNative.cs
    src/OpenTK/Platform/X11/XI2MouseKeyboard.cs
```

One thing I do not like is the removal of new-line characters at the end of files. I believe those should be there (and enforced, which [is possible with the `stylecop.json` file](https://github.com/beardgame/utilities/pull/113/files#diff-dd6eef6ebc800ac8221b3e418026479d)).
But others may disagree with that (and I won't pretend it's at all important).

**Comment by Nihlus** [comment]
@amulware Yeah, we ought to enforce newlines since it's POSIX standard. Will activate that rule in another PR.

**Comment by Frassle** [comment]
As good as these style consistency changes are this changeset is probably too large to commit. Is there anyway we can split it up into more reviewable PRs? Diffing this against develop gives "209 files changed, 1997 insertions(+), 1138 deletions(-)", please get that split.

As a first stab at getting that reduced can we pull the binding generator changes and the rerun bind into a new PR. That should be quickly understandable. You don't even need to enable the rules in that PR, so we don't have to do the whole codebase at once.

**Comment by Nihlus** [comment]
While these changes are all fairly related and splitting them will require revisiting files multiple times, I did get a bit carried away with this one. I'm fairly swamped with other things at the moment, but I'll get the generator changes out into a separate PR as soon as possible.

**Comment by varon** [comment]
@Frassle - Couldn't agree more. 
@Nihlus in the interest of keeping our backlog free, going to close this for now. Thanks so much for all the work on the style stuff. We really would like this change, just split up as @Frassle suggests.

I'd also advise we wait on the braces generation until we have zero outstanding PRs again.

**Pull request closed without merging**
